// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// The status of a disease or symptom.
  /// </summary>
  public static class DiseaseStatusCodes
  {
    /// <summary>
    /// Chronic miliary
    /// </summary>
    public static readonly Coding ChronicMiliary = new Coding
    {
      Code = "13550009",
      Display = "Chronic miliary",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Transitory
    /// </summary>
    public static readonly Coding Transitory = new Coding
    {
      Code = "14803004",
      Display = "Transitory",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Acute fulminating
    /// </summary>
    public static readonly Coding AcuteFulminating = new Coding
    {
      Code = "18131002",
      Display = "Acute fulminating",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Subacute
    /// </summary>
    public static readonly Coding Subacute = new Coding
    {
      Code = "19939008",
      Display = "Subacute",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Seasonal
    /// </summary>
    public static readonly Coding Seasonal = new Coding
    {
      Code = "21864008",
      Display = "Seasonal",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Acute-on-chronic
    /// </summary>
    public static readonly Coding AcuteOnChronic = new Coding
    {
      Code = "255212004",
      Display = "Acute-on-chronic",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Recurrent
    /// </summary>
    public static readonly Coding Recurrent = new Coding
    {
      Code = "255227004",
      Display = "Recurrent",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Recurrent acute
    /// </summary>
    public static readonly Coding RecurrentAcute = new Coding
    {
      Code = "255228009",
      Display = "Recurrent acute",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Brittle course
    /// </summary>
    public static readonly Coding BrittleCourse = new Coding
    {
      Code = "255299009",
      Display = "Brittle course",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Progressive
    /// </summary>
    public static readonly Coding Progressive = new Coding
    {
      Code = "255314001",
      Display = "Progressive",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Relapsing course
    /// </summary>
    public static readonly Coding RelapsingCourse = new Coding
    {
      Code = "255318003",
      Display = "Relapsing course",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Remitting
    /// </summary>
    public static readonly Coding Remitting = new Coding
    {
      Code = "255319006",
      Display = "Remitting",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Fluctuating
    /// </summary>
    public static readonly Coding Fluctuating = new Coding
    {
      Code = "255341006",
      Display = "Fluctuating",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic migratory
    /// </summary>
    public static readonly Coding ChronicMigratory = new Coding
    {
      Code = "25649003",
      Display = "Chronic migratory",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Continual
    /// </summary>
    public static readonly Coding Continual = new Coding
    {
      Code = "263730007",
      Display = "Continual",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Cyclical relapsing
    /// </summary>
    public static readonly Coding CyclicalRelapsing = new Coding
    {
      Code = "264498007",
      Display = "Cyclical relapsing",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Paroxysmal
    /// </summary>
    public static readonly Coding Paroxysmal = new Coding
    {
      Code = "26593000",
      Display = "Paroxysmal",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Episodic
    /// </summary>
    public static readonly Coding Episodic = new Coding
    {
      Code = "278499009",
      Display = "Episodic",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Courses
    /// </summary>
    public static readonly Coding Courses = new Coding
    {
      Code = "288524001",
      Display = "Courses",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Acute onset (qualifier value)
    /// </summary>
    public static readonly Coding AcuteOnsetQualifierValue = new Coding
    {
      Code = "373933003",
      Display = "Acute onset (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Subacute onset (qualifier value)
    /// </summary>
    public static readonly Coding SubacuteOnsetQualifierValue = new Coding
    {
      Code = "373935005",
      Display = "Subacute onset (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Sudden onset
    /// </summary>
    public static readonly Coding SuddenOnset = new Coding
    {
      Code = "385315009",
      Display = "Sudden onset",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic aggressive
    /// </summary>
    public static readonly Coding ChronicAggressive = new Coding
    {
      Code = "39196007",
      Display = "Chronic aggressive",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Sudden onset AND/OR short duration (qualifier value)
    /// </summary>
    public static readonly Coding SuddenOnsetANDORShortDurationQualifierValue = new Coding
    {
      Code = "424124008",
      Display = "Sudden onset AND/OR short duration (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Clinical course with short duration (qualifier value)
    /// </summary>
    public static readonly Coding ClinicalCourseWithShortDurationQualifierValue = new Coding
    {
      Code = "424572001",
      Display = "Clinical course with short duration (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Sudden onset AND short duration (qualifier value)
    /// </summary>
    public static readonly Coding SuddenOnsetANDShortDurationQualifierValue = new Coding
    {
      Code = "425323003",
      Display = "Sudden onset AND short duration (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Cyclic
    /// </summary>
    public static readonly Coding Cyclic = new Coding
    {
      Code = "44180009",
      Display = "Cyclic",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic active
    /// </summary>
    public static readonly Coding ChronicActive = new Coding
    {
      Code = "47501007",
      Display = "Chronic active",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic granulomatous
    /// </summary>
    public static readonly Coding ChronicGranulomatous = new Coding
    {
      Code = "50188003",
      Display = "Chronic granulomatous",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Gradual onset
    /// </summary>
    public static readonly Coding GradualOnset = new Coding
    {
      Code = "61751001",
      Display = "Gradual onset",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic persistent
    /// </summary>
    public static readonly Coding ChronicPersistent = new Coding
    {
      Code = "62459000",
      Display = "Chronic persistent",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Non-progressive
    /// </summary>
    public static readonly Coding NonProgressive = new Coding
    {
      Code = "702322003",
      Display = "Non-progressive",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Intermittent
    /// </summary>
    public static readonly Coding Intermittent = new Coding
    {
      Code = "7087005",
      Display = "Intermittent",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Delayed onset (qualifier value)
    /// </summary>
    public static readonly Coding DelayedOnsetQualifierValue = new Coding
    {
      Code = "788800008",
      Display = "Delayed onset (qualifier value)",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// Chronic
    /// </summary>
    public static readonly Coding Chronic = new Coding
    {
      Code = "90734009",
      Display = "Chronic",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: ChronicMiliary
    /// </summary>
    public const string LiteralChronicMiliary = "13550009";

    /// <summary>
    /// Literal for code: NONEChronicMiliary
    /// </summary>
    public const string LiteralNONEChronicMiliary = "http://snomed.info/sct#13550009";

    /// <summary>
    /// Literal for code: Transitory
    /// </summary>
    public const string LiteralTransitory = "14803004";

    /// <summary>
    /// Literal for code: NONETransitory
    /// </summary>
    public const string LiteralNONETransitory = "http://snomed.info/sct#14803004";

    /// <summary>
    /// Literal for code: AcuteFulminating
    /// </summary>
    public const string LiteralAcuteFulminating = "18131002";

    /// <summary>
    /// Literal for code: NONEAcuteFulminating
    /// </summary>
    public const string LiteralNONEAcuteFulminating = "http://snomed.info/sct#18131002";

    /// <summary>
    /// Literal for code: Subacute
    /// </summary>
    public const string LiteralSubacute = "19939008";

    /// <summary>
    /// Literal for code: NONESubacute
    /// </summary>
    public const string LiteralNONESubacute = "http://snomed.info/sct#19939008";

    /// <summary>
    /// Literal for code: Seasonal
    /// </summary>
    public const string LiteralSeasonal = "21864008";

    /// <summary>
    /// Literal for code: NONESeasonal
    /// </summary>
    public const string LiteralNONESeasonal = "http://snomed.info/sct#21864008";

    /// <summary>
    /// Literal for code: AcuteOnChronic
    /// </summary>
    public const string LiteralAcuteOnChronic = "255212004";

    /// <summary>
    /// Literal for code: NONEAcuteOnChronic
    /// </summary>
    public const string LiteralNONEAcuteOnChronic = "http://snomed.info/sct#255212004";

    /// <summary>
    /// Literal for code: Recurrent
    /// </summary>
    public const string LiteralRecurrent = "255227004";

    /// <summary>
    /// Literal for code: NONERecurrent
    /// </summary>
    public const string LiteralNONERecurrent = "http://snomed.info/sct#255227004";

    /// <summary>
    /// Literal for code: RecurrentAcute
    /// </summary>
    public const string LiteralRecurrentAcute = "255228009";

    /// <summary>
    /// Literal for code: NONERecurrentAcute
    /// </summary>
    public const string LiteralNONERecurrentAcute = "http://snomed.info/sct#255228009";

    /// <summary>
    /// Literal for code: BrittleCourse
    /// </summary>
    public const string LiteralBrittleCourse = "255299009";

    /// <summary>
    /// Literal for code: NONEBrittleCourse
    /// </summary>
    public const string LiteralNONEBrittleCourse = "http://snomed.info/sct#255299009";

    /// <summary>
    /// Literal for code: Progressive
    /// </summary>
    public const string LiteralProgressive = "255314001";

    /// <summary>
    /// Literal for code: NONEProgressive
    /// </summary>
    public const string LiteralNONEProgressive = "http://snomed.info/sct#255314001";

    /// <summary>
    /// Literal for code: RelapsingCourse
    /// </summary>
    public const string LiteralRelapsingCourse = "255318003";

    /// <summary>
    /// Literal for code: NONERelapsingCourse
    /// </summary>
    public const string LiteralNONERelapsingCourse = "http://snomed.info/sct#255318003";

    /// <summary>
    /// Literal for code: Remitting
    /// </summary>
    public const string LiteralRemitting = "255319006";

    /// <summary>
    /// Literal for code: NONERemitting
    /// </summary>
    public const string LiteralNONERemitting = "http://snomed.info/sct#255319006";

    /// <summary>
    /// Literal for code: Fluctuating
    /// </summary>
    public const string LiteralFluctuating = "255341006";

    /// <summary>
    /// Literal for code: NONEFluctuating
    /// </summary>
    public const string LiteralNONEFluctuating = "http://snomed.info/sct#255341006";

    /// <summary>
    /// Literal for code: ChronicMigratory
    /// </summary>
    public const string LiteralChronicMigratory = "25649003";

    /// <summary>
    /// Literal for code: NONEChronicMigratory
    /// </summary>
    public const string LiteralNONEChronicMigratory = "http://snomed.info/sct#25649003";

    /// <summary>
    /// Literal for code: Continual
    /// </summary>
    public const string LiteralContinual = "263730007";

    /// <summary>
    /// Literal for code: NONEContinual
    /// </summary>
    public const string LiteralNONEContinual = "http://snomed.info/sct#263730007";

    /// <summary>
    /// Literal for code: CyclicalRelapsing
    /// </summary>
    public const string LiteralCyclicalRelapsing = "264498007";

    /// <summary>
    /// Literal for code: NONECyclicalRelapsing
    /// </summary>
    public const string LiteralNONECyclicalRelapsing = "http://snomed.info/sct#264498007";

    /// <summary>
    /// Literal for code: Paroxysmal
    /// </summary>
    public const string LiteralParoxysmal = "26593000";

    /// <summary>
    /// Literal for code: NONEParoxysmal
    /// </summary>
    public const string LiteralNONEParoxysmal = "http://snomed.info/sct#26593000";

    /// <summary>
    /// Literal for code: Episodic
    /// </summary>
    public const string LiteralEpisodic = "278499009";

    /// <summary>
    /// Literal for code: NONEEpisodic
    /// </summary>
    public const string LiteralNONEEpisodic = "http://snomed.info/sct#278499009";

    /// <summary>
    /// Literal for code: Courses
    /// </summary>
    public const string LiteralCourses = "288524001";

    /// <summary>
    /// Literal for code: NONECourses
    /// </summary>
    public const string LiteralNONECourses = "http://snomed.info/sct#288524001";

    /// <summary>
    /// Literal for code: AcuteOnsetQualifierValue
    /// </summary>
    public const string LiteralAcuteOnsetQualifierValue = "373933003";

    /// <summary>
    /// Literal for code: NONEAcuteOnsetQualifierValue
    /// </summary>
    public const string LiteralNONEAcuteOnsetQualifierValue = "http://snomed.info/sct#373933003";

    /// <summary>
    /// Literal for code: SubacuteOnsetQualifierValue
    /// </summary>
    public const string LiteralSubacuteOnsetQualifierValue = "373935005";

    /// <summary>
    /// Literal for code: NONESubacuteOnsetQualifierValue
    /// </summary>
    public const string LiteralNONESubacuteOnsetQualifierValue = "http://snomed.info/sct#373935005";

    /// <summary>
    /// Literal for code: SuddenOnset
    /// </summary>
    public const string LiteralSuddenOnset = "385315009";

    /// <summary>
    /// Literal for code: NONESuddenOnset
    /// </summary>
    public const string LiteralNONESuddenOnset = "http://snomed.info/sct#385315009";

    /// <summary>
    /// Literal for code: ChronicAggressive
    /// </summary>
    public const string LiteralChronicAggressive = "39196007";

    /// <summary>
    /// Literal for code: NONEChronicAggressive
    /// </summary>
    public const string LiteralNONEChronicAggressive = "http://snomed.info/sct#39196007";

    /// <summary>
    /// Literal for code: SuddenOnsetANDORShortDurationQualifierValue
    /// </summary>
    public const string LiteralSuddenOnsetANDORShortDurationQualifierValue = "424124008";

    /// <summary>
    /// Literal for code: NONESuddenOnsetANDORShortDurationQualifierValue
    /// </summary>
    public const string LiteralNONESuddenOnsetANDORShortDurationQualifierValue = "http://snomed.info/sct#424124008";

    /// <summary>
    /// Literal for code: ClinicalCourseWithShortDurationQualifierValue
    /// </summary>
    public const string LiteralClinicalCourseWithShortDurationQualifierValue = "424572001";

    /// <summary>
    /// Literal for code: NONEClinicalCourseWithShortDurationQualifierValue
    /// </summary>
    public const string LiteralNONEClinicalCourseWithShortDurationQualifierValue = "http://snomed.info/sct#424572001";

    /// <summary>
    /// Literal for code: SuddenOnsetANDShortDurationQualifierValue
    /// </summary>
    public const string LiteralSuddenOnsetANDShortDurationQualifierValue = "425323003";

    /// <summary>
    /// Literal for code: NONESuddenOnsetANDShortDurationQualifierValue
    /// </summary>
    public const string LiteralNONESuddenOnsetANDShortDurationQualifierValue = "http://snomed.info/sct#425323003";

    /// <summary>
    /// Literal for code: Cyclic
    /// </summary>
    public const string LiteralCyclic = "44180009";

    /// <summary>
    /// Literal for code: NONECyclic
    /// </summary>
    public const string LiteralNONECyclic = "http://snomed.info/sct#44180009";

    /// <summary>
    /// Literal for code: ChronicActive
    /// </summary>
    public const string LiteralChronicActive = "47501007";

    /// <summary>
    /// Literal for code: NONEChronicActive
    /// </summary>
    public const string LiteralNONEChronicActive = "http://snomed.info/sct#47501007";

    /// <summary>
    /// Literal for code: ChronicGranulomatous
    /// </summary>
    public const string LiteralChronicGranulomatous = "50188003";

    /// <summary>
    /// Literal for code: NONEChronicGranulomatous
    /// </summary>
    public const string LiteralNONEChronicGranulomatous = "http://snomed.info/sct#50188003";

    /// <summary>
    /// Literal for code: GradualOnset
    /// </summary>
    public const string LiteralGradualOnset = "61751001";

    /// <summary>
    /// Literal for code: NONEGradualOnset
    /// </summary>
    public const string LiteralNONEGradualOnset = "http://snomed.info/sct#61751001";

    /// <summary>
    /// Literal for code: ChronicPersistent
    /// </summary>
    public const string LiteralChronicPersistent = "62459000";

    /// <summary>
    /// Literal for code: NONEChronicPersistent
    /// </summary>
    public const string LiteralNONEChronicPersistent = "http://snomed.info/sct#62459000";

    /// <summary>
    /// Literal for code: NonProgressive
    /// </summary>
    public const string LiteralNonProgressive = "702322003";

    /// <summary>
    /// Literal for code: NONENonProgressive
    /// </summary>
    public const string LiteralNONENonProgressive = "http://snomed.info/sct#702322003";

    /// <summary>
    /// Literal for code: Intermittent
    /// </summary>
    public const string LiteralIntermittent = "7087005";

    /// <summary>
    /// Literal for code: NONEIntermittent
    /// </summary>
    public const string LiteralNONEIntermittent = "http://snomed.info/sct#7087005";

    /// <summary>
    /// Literal for code: DelayedOnsetQualifierValue
    /// </summary>
    public const string LiteralDelayedOnsetQualifierValue = "788800008";

    /// <summary>
    /// Literal for code: NONEDelayedOnsetQualifierValue
    /// </summary>
    public const string LiteralNONEDelayedOnsetQualifierValue = "http://snomed.info/sct#788800008";

    /// <summary>
    /// Literal for code: Chronic
    /// </summary>
    public const string LiteralChronic = "90734009";

    /// <summary>
    /// Literal for code: NONEChronic
    /// </summary>
    public const string LiteralNONEChronic = "http://snomed.info/sct#90734009";

    /// <summary>
    /// Dictionary for looking up DiseaseStatus Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "13550009", ChronicMiliary }, 
      { "http://snomed.info/sct#13550009", ChronicMiliary }, 
      { "14803004", Transitory }, 
      { "http://snomed.info/sct#14803004", Transitory }, 
      { "18131002", AcuteFulminating }, 
      { "http://snomed.info/sct#18131002", AcuteFulminating }, 
      { "19939008", Subacute }, 
      { "http://snomed.info/sct#19939008", Subacute }, 
      { "21864008", Seasonal }, 
      { "http://snomed.info/sct#21864008", Seasonal }, 
      { "255212004", AcuteOnChronic }, 
      { "http://snomed.info/sct#255212004", AcuteOnChronic }, 
      { "255227004", Recurrent }, 
      { "http://snomed.info/sct#255227004", Recurrent }, 
      { "255228009", RecurrentAcute }, 
      { "http://snomed.info/sct#255228009", RecurrentAcute }, 
      { "255299009", BrittleCourse }, 
      { "http://snomed.info/sct#255299009", BrittleCourse }, 
      { "255314001", Progressive }, 
      { "http://snomed.info/sct#255314001", Progressive }, 
      { "255318003", RelapsingCourse }, 
      { "http://snomed.info/sct#255318003", RelapsingCourse }, 
      { "255319006", Remitting }, 
      { "http://snomed.info/sct#255319006", Remitting }, 
      { "255341006", Fluctuating }, 
      { "http://snomed.info/sct#255341006", Fluctuating }, 
      { "25649003", ChronicMigratory }, 
      { "http://snomed.info/sct#25649003", ChronicMigratory }, 
      { "263730007", Continual }, 
      { "http://snomed.info/sct#263730007", Continual }, 
      { "264498007", CyclicalRelapsing }, 
      { "http://snomed.info/sct#264498007", CyclicalRelapsing }, 
      { "26593000", Paroxysmal }, 
      { "http://snomed.info/sct#26593000", Paroxysmal }, 
      { "278499009", Episodic }, 
      { "http://snomed.info/sct#278499009", Episodic }, 
      { "288524001", Courses }, 
      { "http://snomed.info/sct#288524001", Courses }, 
      { "373933003", AcuteOnsetQualifierValue }, 
      { "http://snomed.info/sct#373933003", AcuteOnsetQualifierValue }, 
      { "373935005", SubacuteOnsetQualifierValue }, 
      { "http://snomed.info/sct#373935005", SubacuteOnsetQualifierValue }, 
      { "385315009", SuddenOnset }, 
      { "http://snomed.info/sct#385315009", SuddenOnset }, 
      { "39196007", ChronicAggressive }, 
      { "http://snomed.info/sct#39196007", ChronicAggressive }, 
      { "424124008", SuddenOnsetANDORShortDurationQualifierValue }, 
      { "http://snomed.info/sct#424124008", SuddenOnsetANDORShortDurationQualifierValue }, 
      { "424572001", ClinicalCourseWithShortDurationQualifierValue }, 
      { "http://snomed.info/sct#424572001", ClinicalCourseWithShortDurationQualifierValue }, 
      { "425323003", SuddenOnsetANDShortDurationQualifierValue }, 
      { "http://snomed.info/sct#425323003", SuddenOnsetANDShortDurationQualifierValue }, 
      { "44180009", Cyclic }, 
      { "http://snomed.info/sct#44180009", Cyclic }, 
      { "47501007", ChronicActive }, 
      { "http://snomed.info/sct#47501007", ChronicActive }, 
      { "50188003", ChronicGranulomatous }, 
      { "http://snomed.info/sct#50188003", ChronicGranulomatous }, 
      { "61751001", GradualOnset }, 
      { "http://snomed.info/sct#61751001", GradualOnset }, 
      { "62459000", ChronicPersistent }, 
      { "http://snomed.info/sct#62459000", ChronicPersistent }, 
      { "702322003", NonProgressive }, 
      { "http://snomed.info/sct#702322003", NonProgressive }, 
      { "7087005", Intermittent }, 
      { "http://snomed.info/sct#7087005", Intermittent }, 
      { "788800008", DelayedOnsetQualifierValue }, 
      { "http://snomed.info/sct#788800008", DelayedOnsetQualifierValue }, 
      { "90734009", Chronic }, 
      { "http://snomed.info/sct#90734009", Chronic }, 
    };
  };
}
