// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// The media type of the expression language.
  /// </summary>
  public static class ExpressionLanguageCodes
  {
    /// <summary>
    /// FHIR's RESTful query syntax - typically independent of base URL.
    /// </summary>
    public static readonly Coding FHIRQuery = new Coding
    {
      Code = "application/x-fhir-query",
      Display = "FHIR Query",
      System = "http://hl7.org/fhir/expression-language"
    };
    /// <summary>
    /// Clinical Quality Language.
    /// </summary>
    public static readonly Coding CQL = new Coding
    {
      Code = "text/cql",
      Display = "CQL",
      System = "http://hl7.org/fhir/expression-language"
    };
    /// <summary>
    /// A Clinical Quality Language expression.
    /// </summary>
    public static readonly Coding CQLExpression = new Coding
    {
      Code = "text/cql-expression",
      Display = "CQL Expression",
      System = "http://hl7.org/fhir/expression-language"
    };
    /// <summary>
    /// A valid Clinical Quality Language identifier.
    /// </summary>
    public static readonly Coding CQLIdentifier = new Coding
    {
      Code = "text/cql-identifier",
      Display = "CQL Identifier",
      System = "http://hl7.org/fhir/expression-language"
    };
    /// <summary>
    /// FHIRPath.
    /// </summary>
    public static readonly Coding FHIRPath = new Coding
    {
      Code = "text/fhirpath",
      Display = "FHIRPath",
      System = "http://hl7.org/fhir/expression-language"
    };

    /// <summary>
    /// Literal for code: FHIRQuery
    /// </summary>
    public const string LiteralFHIRQuery = "application/x-fhir-query";

    /// <summary>
    /// Literal for code: ExpressionLanguageFHIRQuery
    /// </summary>
    public const string LiteralExpressionLanguageFHIRQuery = "http://hl7.org/fhir/expression-language#application/x-fhir-query";

    /// <summary>
    /// Literal for code: CQL
    /// </summary>
    public const string LiteralCQL = "text/cql";

    /// <summary>
    /// Literal for code: ExpressionLanguageCQL
    /// </summary>
    public const string LiteralExpressionLanguageCQL = "http://hl7.org/fhir/expression-language#text/cql";

    /// <summary>
    /// Literal for code: CQLExpression
    /// </summary>
    public const string LiteralCQLExpression = "text/cql-expression";

    /// <summary>
    /// Literal for code: ExpressionLanguageCQLExpression
    /// </summary>
    public const string LiteralExpressionLanguageCQLExpression = "http://hl7.org/fhir/expression-language#text/cql-expression";

    /// <summary>
    /// Literal for code: CQLIdentifier
    /// </summary>
    public const string LiteralCQLIdentifier = "text/cql-identifier";

    /// <summary>
    /// Literal for code: ExpressionLanguageCQLIdentifier
    /// </summary>
    public const string LiteralExpressionLanguageCQLIdentifier = "http://hl7.org/fhir/expression-language#text/cql-identifier";

    /// <summary>
    /// Literal for code: FHIRPath
    /// </summary>
    public const string LiteralFHIRPath = "text/fhirpath";

    /// <summary>
    /// Literal for code: ExpressionLanguageFHIRPath
    /// </summary>
    public const string LiteralExpressionLanguageFHIRPath = "http://hl7.org/fhir/expression-language#text/fhirpath";

    /// <summary>
    /// Dictionary for looking up ExpressionLanguage Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "application/x-fhir-query", FHIRQuery }, 
      { "http://hl7.org/fhir/expression-language#application/x-fhir-query", FHIRQuery }, 
      { "text/cql", CQL }, 
      { "http://hl7.org/fhir/expression-language#text/cql", CQL }, 
      { "text/cql-expression", CQLExpression }, 
      { "http://hl7.org/fhir/expression-language#text/cql-expression", CQLExpression }, 
      { "text/cql-identifier", CQLIdentifier }, 
      { "http://hl7.org/fhir/expression-language#text/cql-identifier", CQLIdentifier }, 
      { "text/fhirpath", FHIRPath }, 
      { "http://hl7.org/fhir/expression-language#text/fhirpath", FHIRPath }, 
    };
  };
}
