// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// Detailed information about the type of the image - its kind, purpose, or the kind of equipment used to generate it.
  /// </summary>
  public static class MediaModalityCodes
  {
    /// <summary>
    /// Autorefraction device
    /// </summary>
    public static readonly Coding Autorefraction_dicom_dcim = new Coding
    {
      Code = "AR",
      Display = "Autorefraction",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Ultrasound Bone Densitometry (modality)
    /// </summary>
    public static readonly Coding UltrasoundBoneDensitometry_dicom_dcim = new Coding
    {
      Code = "BDUS",
      Display = "Ultrasound Bone Densitometry",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Biomagnetic imaging device
    /// </summary>
    public static readonly Coding BiomagneticImaging_dicom_dcim = new Coding
    {
      Code = "BI",
      Display = "Biomagnetic imaging",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Bone Mineral Densitometry by X-Ray (modality), including dual-energy X-Ray absorptiometry (DXA) and morphometric X-Ray absorptiometry (MXA)
    /// </summary>
    public static readonly Coding BoneMineralDensitometry_dicom_dcim = new Coding
    {
      Code = "BMD",
      Display = "Bone Mineral Densitometry",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Computed Radiography device
    /// </summary>
    public static readonly Coding ComputedRadiography_dicom_dcim = new Coding
    {
      Code = "CR",
      Display = "Computed Radiography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Computed Tomography device
    /// </summary>
    public static readonly Coding ComputedTomography_dicom_dcim = new Coding
    {
      Code = "CT",
      Display = "Computed Tomography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Diaphanography device
    /// </summary>
    public static readonly Coding Diaphanography_dicom_dcim = new Coding
    {
      Code = "DG",
      Display = "Diaphanography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// A diagram. Often used in diagnostic reports
    /// </summary>
    public static readonly Coding Diagram_media_modality = new Coding
    {
      Code = "diagram",
      Display = "Diagram",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// Dermoscopy
    /// </summary>
    public static readonly Coding Dermoscopy_ = new Coding
    {
      Code = "DMS",
      Display = "Dermoscopy",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Digital Radiography device
    /// </summary>
    public static readonly Coding DigitalRadiography_dicom_dcim = new Coding
    {
      Code = "DX",
      Display = "Digital Radiography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Electrocardiography device
    /// </summary>
    public static readonly Coding Electrocardiography_dicom_dcim = new Coding
    {
      Code = "ECG",
      Display = "Electrocardiography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Electroencephalography
    /// </summary>
    public static readonly Coding Electroencephalography_ = new Coding
    {
      Code = "EEG",
      Display = "Electroencephalography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Electromyography
    /// </summary>
    public static readonly Coding Electromyography_ = new Coding
    {
      Code = "EMG",
      Display = "Electromyography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Electrooculography
    /// </summary>
    public static readonly Coding Electrooculography_ = new Coding
    {
      Code = "EOG",
      Display = "Electrooculography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Cardiac Electrophysiology device
    /// </summary>
    public static readonly Coding CardiacElectrophysiology_dicom_dcim = new Coding
    {
      Code = "EPS",
      Display = "Cardiac Electrophysiology",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Endoscopy device
    /// </summary>
    public static readonly Coding Endoscopy_dicom_dcim = new Coding
    {
      Code = "ES",
      Display = "Endoscopy",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// A face scan used for identification purposes
    /// </summary>
    public static readonly Coding FaceScan_media_modality = new Coding
    {
      Code = "face",
      Display = "Face Scan",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// A digital record of a fax document
    /// </summary>
    public static readonly Coding Fax_media_modality = new Coding
    {
      Code = "fax",
      Display = "Fax",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// A finger print scan used for identification purposes
    /// </summary>
    public static readonly Coding Fingerprint_media_modality = new Coding
    {
      Code = "fingerprint",
      Display = "Fingerprint",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// General Microscopy device
    /// </summary>
    public static readonly Coding GeneralMicroscopy_dicom_dcim = new Coding
    {
      Code = "GM",
      Display = "General Microscopy",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Hemodynamic Waveform acquisition device
    /// </summary>
    public static readonly Coding HemodynamicWaveform_dicom_dcim = new Coding
    {
      Code = "HD",
      Display = "Hemodynamic Waveform",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Intra-oral Radiography device
    /// </summary>
    public static readonly Coding IntraOralRadiography_dicom_dcim = new Coding
    {
      Code = "IO",
      Display = "Intra-oral Radiography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// An iris scan used for identification purposes
    /// </summary>
    public static readonly Coding IrisScan_media_modality = new Coding
    {
      Code = "iris",
      Display = "Iris Scan",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// An acquisition device, process or method that performs intravascular optical coherence tomography
    /// </summary>
    public static readonly Coding IntravascularOpticalCoherenceTomography_dicom_dcim = new Coding
    {
      Code = "IVOCT",
      Display = "Intravascular Optical Coherence Tomography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Intravascular Ultrasound device
    /// </summary>
    public static readonly Coding IntravascularUltrasound_dicom_dcim = new Coding
    {
      Code = "IVUS",
      Display = "Intravascular Ultrasound",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Keratometry device
    /// </summary>
    public static readonly Coding Keratometry_dicom_dcim = new Coding
    {
      Code = "KER",
      Display = "Keratometry",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Lensometry device
    /// </summary>
    public static readonly Coding Lensometry_dicom_dcim = new Coding
    {
      Code = "LEN",
      Display = "Lensometry",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Laser surface scan device
    /// </summary>
    public static readonly Coding LaserSurfaceScan_dicom_dcim = new Coding
    {
      Code = "LS",
      Display = "Laser surface scan",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Mammography device
    /// </summary>
    public static readonly Coding Mammography_dicom_dcim = new Coding
    {
      Code = "MG",
      Display = "Mammography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Magnetic Resonance device
    /// </summary>
    public static readonly Coding MagneticResonance_dicom_dcim = new Coding
    {
      Code = "MR",
      Display = "Magnetic Resonance",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Nuclear Medicine device
    /// </summary>
    public static readonly Coding NuclearMedicine_dicom_dcim = new Coding
    {
      Code = "NM",
      Display = "Nuclear Medicine",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Measurements of the axial length of the eye, which are done by various devices
    /// </summary>
    public static readonly Coding OphthalmicAxialMeasurements_dicom_dcim = new Coding
    {
      Code = "OAM",
      Display = "Ophthalmic Axial Measurements",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Modality device that uses an interferometric, non-invasive optical tomographic technique to image 2D slices and 3D volumes of tissue using visible and near visible frequencies
    /// </summary>
    public static readonly Coding OpticalCoherenceTomography_dicom_dcim = new Coding
    {
      Code = "OCT",
      Display = "Optical Coherence Tomography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Ophthalmic photography modality
    /// </summary>
    public static readonly Coding OphthalmicPhotography_dicom_dcim = new Coding
    {
      Code = "OP",
      Display = "Ophthalmic photography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Modality device that measures corneal topography, corneal or retinal thickness, and other similar parameters that are typically displayed as maps
    /// </summary>
    public static readonly Coding OphthalmicMapping_dicom_dcim = new Coding
    {
      Code = "OPM",
      Display = "Ophthalmic Mapping",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Tomography of the eye acquired by a modality that is based on light and optical principles. Tomography based on other principles, such as ultrasound, is excluded
    /// </summary>
    public static readonly Coding OphthalmicTomography_dicom_dcim = new Coding
    {
      Code = "OPT",
      Display = "Ophthalmic Tomography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Ophthalmic Tomography B-scan Volume Analysis
    /// </summary>
    public static readonly Coding OphthalmicTomographyBScanVolumeAnalysis_ = new Coding
    {
      Code = "OPTBSV",
      Display = "Ophthalmic Tomography B-scan Volume Analysis",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Ophthalmic Tomography En Face
    /// </summary>
    public static readonly Coding OphthalmicTomographyEnFace_ = new Coding
    {
      Code = "OPTENF",
      Display = "Ophthalmic Tomography En Face",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Modality device that measures visual fields and perform visual perimetry
    /// </summary>
    public static readonly Coding OphthalmicVisualField_dicom_dcim = new Coding
    {
      Code = "OPV",
      Display = "Ophthalmic Visual Field",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// An acquisition device, process or method that performs optical surface scanning
    /// </summary>
    public static readonly Coding OpticalSurvaceScanner_dicom_dcim = new Coding
    {
      Code = "OSS",
      Display = "Optical Survace Scanner",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// A palm scan used for identification purposes
    /// </summary>
    public static readonly Coding PalmScan_media_modality = new Coding
    {
      Code = "palm",
      Display = "Palm Scan",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// Position Sensor
    /// </summary>
    public static readonly Coding PositionSensor_ = new Coding
    {
      Code = "POS",
      Display = "Position Sensor",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Positron emission tomography (PET) device
    /// </summary>
    public static readonly Coding PositronEmissionTomography_dicom_dcim = new Coding
    {
      Code = "PT",
      Display = "Positron emission tomography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Panoramic X-Ray device
    /// </summary>
    public static readonly Coding PanoramicXRay_dicom_dcim = new Coding
    {
      Code = "PX",
      Display = "Panoramic X-Ray",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Respiratory Waveform
    /// </summary>
    public static readonly Coding RespiratoryWaveform_ = new Coding
    {
      Code = "RESP",
      Display = "Respiratory Waveform",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// A retinal image used for identification purposes
    /// </summary>
    public static readonly Coding RetinaScan_media_modality = new Coding
    {
      Code = "retina",
      Display = "Retina Scan",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// Radiofluoroscopy device
    /// </summary>
    public static readonly Coding Radiofluoroscopy_dicom_dcim = new Coding
    {
      Code = "RF",
      Display = "Radiofluoroscopy",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Radiographic imaging (conventional film/screen)
    /// </summary>
    public static readonly Coding RadiographicImaging_dicom_dcim = new Coding
    {
      Code = "RG",
      Display = "Radiographic imaging",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Radiotherapy Imaging device; includes portal imaging
    /// </summary>
    public static readonly Coding RadiotherapyImage_dicom_dcim = new Coding
    {
      Code = "RTIMAGE",
      Display = "Radiotherapy Image",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// A digital scan of a document. This is reserved for when there is not enough metadata to create a document reference
    /// </summary>
    public static readonly Coding ScannedDocument_media_modality = new Coding
    {
      Code = "scan",
      Display = "Scanned Document",
      System = "http://terminology.hl7.org/CodeSystem/media-modality"
    };
    /// <summary>
    /// Slide Microscopy
    /// </summary>
    public static readonly Coding SlideMicroscopy_dicom_dcim = new Coding
    {
      Code = "SM",
      Display = "Slide Microscopy",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Subjective Refraction device
    /// </summary>
    public static readonly Coding SubjectiveRefraction_dicom_dcim = new Coding
    {
      Code = "SRF",
      Display = "Subjective Refraction",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Thermography device
    /// </summary>
    public static readonly Coding Thermography_dicom_dcim = new Coding
    {
      Code = "TG",
      Display = "Thermography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Ultrasound device
    /// </summary>
    public static readonly Coding Ultrasound_dicom_dcim = new Coding
    {
      Code = "US",
      Display = "Ultrasound",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// Visual Acuity device
    /// </summary>
    public static readonly Coding VisualAcuity_dicom_dcim = new Coding
    {
      Code = "VA",
      Display = "Visual Acuity",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// X-Ray Angiography device
    /// </summary>
    public static readonly Coding XRayAngiography_dicom_dcim = new Coding
    {
      Code = "XA",
      Display = "X-Ray Angiography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };
    /// <summary>
    /// External-camera Photography device
    /// </summary>
    public static readonly Coding ExternalCameraPhotography_dicom_dcim = new Coding
    {
      Code = "XC",
      Display = "External-camera Photography",
      System = "http://dicom.nema.org/resources/ontology/DCM"
    };

    /// <summary>
    /// Literal for code: Autorefraction_dicom_dcim
    /// </summary>
    public const string LiteralAutorefraction_dicom_dcim = "AR";

    /// <summary>
    /// Literal for code: DicomDcimAutorefraction_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimAutorefraction_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#AR";

    /// <summary>
    /// Literal for code: UltrasoundBoneDensitometry_dicom_dcim
    /// </summary>
    public const string LiteralUltrasoundBoneDensitometry_dicom_dcim = "BDUS";

    /// <summary>
    /// Literal for code: DicomDcimUltrasoundBoneDensitometry_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimUltrasoundBoneDensitometry_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#BDUS";

    /// <summary>
    /// Literal for code: BiomagneticImaging_dicom_dcim
    /// </summary>
    public const string LiteralBiomagneticImaging_dicom_dcim = "BI";

    /// <summary>
    /// Literal for code: DicomDcimBiomagneticImaging_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimBiomagneticImaging_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#BI";

    /// <summary>
    /// Literal for code: BoneMineralDensitometry_dicom_dcim
    /// </summary>
    public const string LiteralBoneMineralDensitometry_dicom_dcim = "BMD";

    /// <summary>
    /// Literal for code: DicomDcimBoneMineralDensitometry_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimBoneMineralDensitometry_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#BMD";

    /// <summary>
    /// Literal for code: ComputedRadiography_dicom_dcim
    /// </summary>
    public const string LiteralComputedRadiography_dicom_dcim = "CR";

    /// <summary>
    /// Literal for code: DicomDcimComputedRadiography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimComputedRadiography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#CR";

    /// <summary>
    /// Literal for code: ComputedTomography_dicom_dcim
    /// </summary>
    public const string LiteralComputedTomography_dicom_dcim = "CT";

    /// <summary>
    /// Literal for code: DicomDcimComputedTomography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimComputedTomography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#CT";

    /// <summary>
    /// Literal for code: Diaphanography_dicom_dcim
    /// </summary>
    public const string LiteralDiaphanography_dicom_dcim = "DG";

    /// <summary>
    /// Literal for code: DicomDcimDiaphanography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimDiaphanography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#DG";

    /// <summary>
    /// Literal for code: Diagram_media_modality
    /// </summary>
    public const string LiteralDiagram_media_modality = "diagram";

    /// <summary>
    /// Literal for code: MediaModalityDiagram_media_modality
    /// </summary>
    public const string LiteralMediaModalityDiagram_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#diagram";

    /// <summary>
    /// Literal for code: Dermoscopy_
    /// </summary>
    public const string LiteralDermoscopy_ = "DMS";

    /// <summary>
    /// Literal for code: NONEDermoscopy_
    /// </summary>
    public const string LiteralNONEDermoscopy_ = "http://dicom.nema.org/resources/ontology/DCM#DMS";

    /// <summary>
    /// Literal for code: DigitalRadiography_dicom_dcim
    /// </summary>
    public const string LiteralDigitalRadiography_dicom_dcim = "DX";

    /// <summary>
    /// Literal for code: DicomDcimDigitalRadiography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimDigitalRadiography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#DX";

    /// <summary>
    /// Literal for code: Electrocardiography_dicom_dcim
    /// </summary>
    public const string LiteralElectrocardiography_dicom_dcim = "ECG";

    /// <summary>
    /// Literal for code: DicomDcimElectrocardiography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimElectrocardiography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#ECG";

    /// <summary>
    /// Literal for code: Electroencephalography_
    /// </summary>
    public const string LiteralElectroencephalography_ = "EEG";

    /// <summary>
    /// Literal for code: NONEElectroencephalography_
    /// </summary>
    public const string LiteralNONEElectroencephalography_ = "http://dicom.nema.org/resources/ontology/DCM#EEG";

    /// <summary>
    /// Literal for code: Electromyography_
    /// </summary>
    public const string LiteralElectromyography_ = "EMG";

    /// <summary>
    /// Literal for code: NONEElectromyography_
    /// </summary>
    public const string LiteralNONEElectromyography_ = "http://dicom.nema.org/resources/ontology/DCM#EMG";

    /// <summary>
    /// Literal for code: Electrooculography_
    /// </summary>
    public const string LiteralElectrooculography_ = "EOG";

    /// <summary>
    /// Literal for code: NONEElectrooculography_
    /// </summary>
    public const string LiteralNONEElectrooculography_ = "http://dicom.nema.org/resources/ontology/DCM#EOG";

    /// <summary>
    /// Literal for code: CardiacElectrophysiology_dicom_dcim
    /// </summary>
    public const string LiteralCardiacElectrophysiology_dicom_dcim = "EPS";

    /// <summary>
    /// Literal for code: DicomDcimCardiacElectrophysiology_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimCardiacElectrophysiology_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#EPS";

    /// <summary>
    /// Literal for code: Endoscopy_dicom_dcim
    /// </summary>
    public const string LiteralEndoscopy_dicom_dcim = "ES";

    /// <summary>
    /// Literal for code: DicomDcimEndoscopy_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimEndoscopy_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#ES";

    /// <summary>
    /// Literal for code: FaceScan_media_modality
    /// </summary>
    public const string LiteralFaceScan_media_modality = "face";

    /// <summary>
    /// Literal for code: MediaModalityFaceScan_media_modality
    /// </summary>
    public const string LiteralMediaModalityFaceScan_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#face";

    /// <summary>
    /// Literal for code: Fax_media_modality
    /// </summary>
    public const string LiteralFax_media_modality = "fax";

    /// <summary>
    /// Literal for code: MediaModalityFax_media_modality
    /// </summary>
    public const string LiteralMediaModalityFax_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#fax";

    /// <summary>
    /// Literal for code: Fingerprint_media_modality
    /// </summary>
    public const string LiteralFingerprint_media_modality = "fingerprint";

    /// <summary>
    /// Literal for code: MediaModalityFingerprint_media_modality
    /// </summary>
    public const string LiteralMediaModalityFingerprint_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#fingerprint";

    /// <summary>
    /// Literal for code: GeneralMicroscopy_dicom_dcim
    /// </summary>
    public const string LiteralGeneralMicroscopy_dicom_dcim = "GM";

    /// <summary>
    /// Literal for code: DicomDcimGeneralMicroscopy_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimGeneralMicroscopy_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#GM";

    /// <summary>
    /// Literal for code: HemodynamicWaveform_dicom_dcim
    /// </summary>
    public const string LiteralHemodynamicWaveform_dicom_dcim = "HD";

    /// <summary>
    /// Literal for code: DicomDcimHemodynamicWaveform_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimHemodynamicWaveform_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#HD";

    /// <summary>
    /// Literal for code: IntraOralRadiography_dicom_dcim
    /// </summary>
    public const string LiteralIntraOralRadiography_dicom_dcim = "IO";

    /// <summary>
    /// Literal for code: DicomDcimIntraOralRadiography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimIntraOralRadiography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#IO";

    /// <summary>
    /// Literal for code: IrisScan_media_modality
    /// </summary>
    public const string LiteralIrisScan_media_modality = "iris";

    /// <summary>
    /// Literal for code: MediaModalityIrisScan_media_modality
    /// </summary>
    public const string LiteralMediaModalityIrisScan_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#iris";

    /// <summary>
    /// Literal for code: IntravascularOpticalCoherenceTomography_dicom_dcim
    /// </summary>
    public const string LiteralIntravascularOpticalCoherenceTomography_dicom_dcim = "IVOCT";

    /// <summary>
    /// Literal for code: DicomDcimIntravascularOpticalCoherenceTomography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimIntravascularOpticalCoherenceTomography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#IVOCT";

    /// <summary>
    /// Literal for code: IntravascularUltrasound_dicom_dcim
    /// </summary>
    public const string LiteralIntravascularUltrasound_dicom_dcim = "IVUS";

    /// <summary>
    /// Literal for code: DicomDcimIntravascularUltrasound_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimIntravascularUltrasound_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#IVUS";

    /// <summary>
    /// Literal for code: Keratometry_dicom_dcim
    /// </summary>
    public const string LiteralKeratometry_dicom_dcim = "KER";

    /// <summary>
    /// Literal for code: DicomDcimKeratometry_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimKeratometry_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#KER";

    /// <summary>
    /// Literal for code: Lensometry_dicom_dcim
    /// </summary>
    public const string LiteralLensometry_dicom_dcim = "LEN";

    /// <summary>
    /// Literal for code: DicomDcimLensometry_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimLensometry_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#LEN";

    /// <summary>
    /// Literal for code: LaserSurfaceScan_dicom_dcim
    /// </summary>
    public const string LiteralLaserSurfaceScan_dicom_dcim = "LS";

    /// <summary>
    /// Literal for code: DicomDcimLaserSurfaceScan_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimLaserSurfaceScan_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#LS";

    /// <summary>
    /// Literal for code: Mammography_dicom_dcim
    /// </summary>
    public const string LiteralMammography_dicom_dcim = "MG";

    /// <summary>
    /// Literal for code: DicomDcimMammography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimMammography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#MG";

    /// <summary>
    /// Literal for code: MagneticResonance_dicom_dcim
    /// </summary>
    public const string LiteralMagneticResonance_dicom_dcim = "MR";

    /// <summary>
    /// Literal for code: DicomDcimMagneticResonance_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimMagneticResonance_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#MR";

    /// <summary>
    /// Literal for code: NuclearMedicine_dicom_dcim
    /// </summary>
    public const string LiteralNuclearMedicine_dicom_dcim = "NM";

    /// <summary>
    /// Literal for code: DicomDcimNuclearMedicine_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimNuclearMedicine_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#NM";

    /// <summary>
    /// Literal for code: OphthalmicAxialMeasurements_dicom_dcim
    /// </summary>
    public const string LiteralOphthalmicAxialMeasurements_dicom_dcim = "OAM";

    /// <summary>
    /// Literal for code: DicomDcimOphthalmicAxialMeasurements_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOphthalmicAxialMeasurements_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OAM";

    /// <summary>
    /// Literal for code: OpticalCoherenceTomography_dicom_dcim
    /// </summary>
    public const string LiteralOpticalCoherenceTomography_dicom_dcim = "OCT";

    /// <summary>
    /// Literal for code: DicomDcimOpticalCoherenceTomography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOpticalCoherenceTomography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OCT";

    /// <summary>
    /// Literal for code: OphthalmicPhotography_dicom_dcim
    /// </summary>
    public const string LiteralOphthalmicPhotography_dicom_dcim = "OP";

    /// <summary>
    /// Literal for code: DicomDcimOphthalmicPhotography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOphthalmicPhotography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OP";

    /// <summary>
    /// Literal for code: OphthalmicMapping_dicom_dcim
    /// </summary>
    public const string LiteralOphthalmicMapping_dicom_dcim = "OPM";

    /// <summary>
    /// Literal for code: DicomDcimOphthalmicMapping_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOphthalmicMapping_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OPM";

    /// <summary>
    /// Literal for code: OphthalmicTomography_dicom_dcim
    /// </summary>
    public const string LiteralOphthalmicTomography_dicom_dcim = "OPT";

    /// <summary>
    /// Literal for code: DicomDcimOphthalmicTomography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOphthalmicTomography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OPT";

    /// <summary>
    /// Literal for code: OphthalmicTomographyBScanVolumeAnalysis_
    /// </summary>
    public const string LiteralOphthalmicTomographyBScanVolumeAnalysis_ = "OPTBSV";

    /// <summary>
    /// Literal for code: NONEOphthalmicTomographyBScanVolumeAnalysis_
    /// </summary>
    public const string LiteralNONEOphthalmicTomographyBScanVolumeAnalysis_ = "http://dicom.nema.org/resources/ontology/DCM#OPTBSV";

    /// <summary>
    /// Literal for code: OphthalmicTomographyEnFace_
    /// </summary>
    public const string LiteralOphthalmicTomographyEnFace_ = "OPTENF";

    /// <summary>
    /// Literal for code: NONEOphthalmicTomographyEnFace_
    /// </summary>
    public const string LiteralNONEOphthalmicTomographyEnFace_ = "http://dicom.nema.org/resources/ontology/DCM#OPTENF";

    /// <summary>
    /// Literal for code: OphthalmicVisualField_dicom_dcim
    /// </summary>
    public const string LiteralOphthalmicVisualField_dicom_dcim = "OPV";

    /// <summary>
    /// Literal for code: DicomDcimOphthalmicVisualField_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOphthalmicVisualField_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OPV";

    /// <summary>
    /// Literal for code: OpticalSurvaceScanner_dicom_dcim
    /// </summary>
    public const string LiteralOpticalSurvaceScanner_dicom_dcim = "OSS";

    /// <summary>
    /// Literal for code: DicomDcimOpticalSurvaceScanner_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimOpticalSurvaceScanner_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#OSS";

    /// <summary>
    /// Literal for code: PalmScan_media_modality
    /// </summary>
    public const string LiteralPalmScan_media_modality = "palm";

    /// <summary>
    /// Literal for code: MediaModalityPalmScan_media_modality
    /// </summary>
    public const string LiteralMediaModalityPalmScan_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#palm";

    /// <summary>
    /// Literal for code: PositionSensor_
    /// </summary>
    public const string LiteralPositionSensor_ = "POS";

    /// <summary>
    /// Literal for code: NONEPositionSensor_
    /// </summary>
    public const string LiteralNONEPositionSensor_ = "http://dicom.nema.org/resources/ontology/DCM#POS";

    /// <summary>
    /// Literal for code: PositronEmissionTomography_dicom_dcim
    /// </summary>
    public const string LiteralPositronEmissionTomography_dicom_dcim = "PT";

    /// <summary>
    /// Literal for code: DicomDcimPositronEmissionTomography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimPositronEmissionTomography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#PT";

    /// <summary>
    /// Literal for code: PanoramicXRay_dicom_dcim
    /// </summary>
    public const string LiteralPanoramicXRay_dicom_dcim = "PX";

    /// <summary>
    /// Literal for code: DicomDcimPanoramicXRay_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimPanoramicXRay_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#PX";

    /// <summary>
    /// Literal for code: RespiratoryWaveform_
    /// </summary>
    public const string LiteralRespiratoryWaveform_ = "RESP";

    /// <summary>
    /// Literal for code: NONERespiratoryWaveform_
    /// </summary>
    public const string LiteralNONERespiratoryWaveform_ = "http://dicom.nema.org/resources/ontology/DCM#RESP";

    /// <summary>
    /// Literal for code: RetinaScan_media_modality
    /// </summary>
    public const string LiteralRetinaScan_media_modality = "retina";

    /// <summary>
    /// Literal for code: MediaModalityRetinaScan_media_modality
    /// </summary>
    public const string LiteralMediaModalityRetinaScan_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#retina";

    /// <summary>
    /// Literal for code: Radiofluoroscopy_dicom_dcim
    /// </summary>
    public const string LiteralRadiofluoroscopy_dicom_dcim = "RF";

    /// <summary>
    /// Literal for code: DicomDcimRadiofluoroscopy_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimRadiofluoroscopy_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#RF";

    /// <summary>
    /// Literal for code: RadiographicImaging_dicom_dcim
    /// </summary>
    public const string LiteralRadiographicImaging_dicom_dcim = "RG";

    /// <summary>
    /// Literal for code: DicomDcimRadiographicImaging_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimRadiographicImaging_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#RG";

    /// <summary>
    /// Literal for code: RadiotherapyImage_dicom_dcim
    /// </summary>
    public const string LiteralRadiotherapyImage_dicom_dcim = "RTIMAGE";

    /// <summary>
    /// Literal for code: DicomDcimRadiotherapyImage_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimRadiotherapyImage_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#RTIMAGE";

    /// <summary>
    /// Literal for code: ScannedDocument_media_modality
    /// </summary>
    public const string LiteralScannedDocument_media_modality = "scan";

    /// <summary>
    /// Literal for code: MediaModalityScannedDocument_media_modality
    /// </summary>
    public const string LiteralMediaModalityScannedDocument_media_modality = "http://terminology.hl7.org/CodeSystem/media-modality#scan";

    /// <summary>
    /// Literal for code: SlideMicroscopy_dicom_dcim
    /// </summary>
    public const string LiteralSlideMicroscopy_dicom_dcim = "SM";

    /// <summary>
    /// Literal for code: DicomDcimSlideMicroscopy_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimSlideMicroscopy_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#SM";

    /// <summary>
    /// Literal for code: SubjectiveRefraction_dicom_dcim
    /// </summary>
    public const string LiteralSubjectiveRefraction_dicom_dcim = "SRF";

    /// <summary>
    /// Literal for code: DicomDcimSubjectiveRefraction_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimSubjectiveRefraction_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#SRF";

    /// <summary>
    /// Literal for code: Thermography_dicom_dcim
    /// </summary>
    public const string LiteralThermography_dicom_dcim = "TG";

    /// <summary>
    /// Literal for code: DicomDcimThermography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimThermography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#TG";

    /// <summary>
    /// Literal for code: Ultrasound_dicom_dcim
    /// </summary>
    public const string LiteralUltrasound_dicom_dcim = "US";

    /// <summary>
    /// Literal for code: DicomDcimUltrasound_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimUltrasound_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#US";

    /// <summary>
    /// Literal for code: VisualAcuity_dicom_dcim
    /// </summary>
    public const string LiteralVisualAcuity_dicom_dcim = "VA";

    /// <summary>
    /// Literal for code: DicomDcimVisualAcuity_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimVisualAcuity_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#VA";

    /// <summary>
    /// Literal for code: XRayAngiography_dicom_dcim
    /// </summary>
    public const string LiteralXRayAngiography_dicom_dcim = "XA";

    /// <summary>
    /// Literal for code: DicomDcimXRayAngiography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimXRayAngiography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#XA";

    /// <summary>
    /// Literal for code: ExternalCameraPhotography_dicom_dcim
    /// </summary>
    public const string LiteralExternalCameraPhotography_dicom_dcim = "XC";

    /// <summary>
    /// Literal for code: DicomDcimExternalCameraPhotography_dicom_dcim
    /// </summary>
    public const string LiteralDicomDcimExternalCameraPhotography_dicom_dcim = "http://dicom.nema.org/resources/ontology/DCM#XC";

    /// <summary>
    /// Dictionary for looking up MediaModality Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "AR", Autorefraction_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#AR", Autorefraction_dicom_dcim }, 
      { "BDUS", UltrasoundBoneDensitometry_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#BDUS", UltrasoundBoneDensitometry_dicom_dcim }, 
      { "BI", BiomagneticImaging_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#BI", BiomagneticImaging_dicom_dcim }, 
      { "BMD", BoneMineralDensitometry_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#BMD", BoneMineralDensitometry_dicom_dcim }, 
      { "CR", ComputedRadiography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#CR", ComputedRadiography_dicom_dcim }, 
      { "CT", ComputedTomography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#CT", ComputedTomography_dicom_dcim }, 
      { "DG", Diaphanography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#DG", Diaphanography_dicom_dcim }, 
      { "diagram", Diagram_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#diagram", Diagram_media_modality }, 
      { "DMS", Dermoscopy_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#DMS", Dermoscopy_ }, 
      { "DX", DigitalRadiography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#DX", DigitalRadiography_dicom_dcim }, 
      { "ECG", Electrocardiography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#ECG", Electrocardiography_dicom_dcim }, 
      { "EEG", Electroencephalography_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#EEG", Electroencephalography_ }, 
      { "EMG", Electromyography_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#EMG", Electromyography_ }, 
      { "EOG", Electrooculography_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#EOG", Electrooculography_ }, 
      { "EPS", CardiacElectrophysiology_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#EPS", CardiacElectrophysiology_dicom_dcim }, 
      { "ES", Endoscopy_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#ES", Endoscopy_dicom_dcim }, 
      { "face", FaceScan_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#face", FaceScan_media_modality }, 
      { "fax", Fax_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#fax", Fax_media_modality }, 
      { "fingerprint", Fingerprint_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#fingerprint", Fingerprint_media_modality }, 
      { "GM", GeneralMicroscopy_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#GM", GeneralMicroscopy_dicom_dcim }, 
      { "HD", HemodynamicWaveform_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#HD", HemodynamicWaveform_dicom_dcim }, 
      { "IO", IntraOralRadiography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#IO", IntraOralRadiography_dicom_dcim }, 
      { "iris", IrisScan_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#iris", IrisScan_media_modality }, 
      { "IVOCT", IntravascularOpticalCoherenceTomography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#IVOCT", IntravascularOpticalCoherenceTomography_dicom_dcim }, 
      { "IVUS", IntravascularUltrasound_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#IVUS", IntravascularUltrasound_dicom_dcim }, 
      { "KER", Keratometry_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#KER", Keratometry_dicom_dcim }, 
      { "LEN", Lensometry_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#LEN", Lensometry_dicom_dcim }, 
      { "LS", LaserSurfaceScan_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#LS", LaserSurfaceScan_dicom_dcim }, 
      { "MG", Mammography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#MG", Mammography_dicom_dcim }, 
      { "MR", MagneticResonance_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#MR", MagneticResonance_dicom_dcim }, 
      { "NM", NuclearMedicine_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#NM", NuclearMedicine_dicom_dcim }, 
      { "OAM", OphthalmicAxialMeasurements_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OAM", OphthalmicAxialMeasurements_dicom_dcim }, 
      { "OCT", OpticalCoherenceTomography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OCT", OpticalCoherenceTomography_dicom_dcim }, 
      { "OP", OphthalmicPhotography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OP", OphthalmicPhotography_dicom_dcim }, 
      { "OPM", OphthalmicMapping_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OPM", OphthalmicMapping_dicom_dcim }, 
      { "OPT", OphthalmicTomography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OPT", OphthalmicTomography_dicom_dcim }, 
      { "OPTBSV", OphthalmicTomographyBScanVolumeAnalysis_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OPTBSV", OphthalmicTomographyBScanVolumeAnalysis_ }, 
      { "OPTENF", OphthalmicTomographyEnFace_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OPTENF", OphthalmicTomographyEnFace_ }, 
      { "OPV", OphthalmicVisualField_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OPV", OphthalmicVisualField_dicom_dcim }, 
      { "OSS", OpticalSurvaceScanner_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#OSS", OpticalSurvaceScanner_dicom_dcim }, 
      { "palm", PalmScan_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#palm", PalmScan_media_modality }, 
      { "POS", PositionSensor_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#POS", PositionSensor_ }, 
      { "PT", PositronEmissionTomography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#PT", PositronEmissionTomography_dicom_dcim }, 
      { "PX", PanoramicXRay_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#PX", PanoramicXRay_dicom_dcim }, 
      { "RESP", RespiratoryWaveform_ }, 
      { "http://dicom.nema.org/resources/ontology/DCM#RESP", RespiratoryWaveform_ }, 
      { "retina", RetinaScan_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#retina", RetinaScan_media_modality }, 
      { "RF", Radiofluoroscopy_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#RF", Radiofluoroscopy_dicom_dcim }, 
      { "RG", RadiographicImaging_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#RG", RadiographicImaging_dicom_dcim }, 
      { "RTIMAGE", RadiotherapyImage_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#RTIMAGE", RadiotherapyImage_dicom_dcim }, 
      { "scan", ScannedDocument_media_modality }, 
      { "http://terminology.hl7.org/CodeSystem/media-modality#scan", ScannedDocument_media_modality }, 
      { "SM", SlideMicroscopy_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#SM", SlideMicroscopy_dicom_dcim }, 
      { "SRF", SubjectiveRefraction_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#SRF", SubjectiveRefraction_dicom_dcim }, 
      { "TG", Thermography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#TG", Thermography_dicom_dcim }, 
      { "US", Ultrasound_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#US", Ultrasound_dicom_dcim }, 
      { "VA", VisualAcuity_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#VA", VisualAcuity_dicom_dcim }, 
      { "XA", XRayAngiography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#XA", XRayAngiography_dicom_dcim }, 
      { "XC", ExternalCameraPhotography_dicom_dcim }, 
      { "http://dicom.nema.org/resources/ontology/DCM#XC", ExternalCameraPhotography_dicom_dcim }, 
    };
  };
}
