// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// A species of origin a substance raw material.
  /// </summary>
  public static class SubstanceSourceMaterialSpeciesCodes
  {
    /// <summary>
    /// Ginkgo biloba
    /// </summary>
    public static readonly Coding GinkgoBiloba = new Coding
    {
      Code = "GinkgoBiloba",
      Display = "Ginkgo biloba",
      System = "http://hl7.org/fhir/substance-source-material-species"
    };
    /// <summary>
    /// Olea europaea
    /// </summary>
    public static readonly Coding OleaEuropaea = new Coding
    {
      Code = "OleaEuropaea",
      Display = "Olea europaea",
      System = "http://hl7.org/fhir/substance-source-material-species"
    };

    /// <summary>
    /// Literal for code: GinkgoBiloba
    /// </summary>
    public const string LiteralGinkgoBiloba = "GinkgoBiloba";

    /// <summary>
    /// Literal for code: SubstanceSourceMaterialSpeciesGinkgoBiloba
    /// </summary>
    public const string LiteralSubstanceSourceMaterialSpeciesGinkgoBiloba = "http://hl7.org/fhir/substance-source-material-species#GinkgoBiloba";

    /// <summary>
    /// Literal for code: OleaEuropaea
    /// </summary>
    public const string LiteralOleaEuropaea = "OleaEuropaea";

    /// <summary>
    /// Literal for code: SubstanceSourceMaterialSpeciesOleaEuropaea
    /// </summary>
    public const string LiteralSubstanceSourceMaterialSpeciesOleaEuropaea = "http://hl7.org/fhir/substance-source-material-species#OleaEuropaea";

    /// <summary>
    /// Dictionary for looking up SubstanceSourceMaterialSpecies Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "GinkgoBiloba", GinkgoBiloba }, 
      { "http://hl7.org/fhir/substance-source-material-species#GinkgoBiloba", GinkgoBiloba }, 
      { "OleaEuropaea", OleaEuropaea }, 
      { "http://hl7.org/fhir/substance-source-material-species#OleaEuropaea", OleaEuropaea }, 
    };
  };
}
