// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// The use context of a substance name for example if there is a different name when used as a drug active ingredient as opposed to a food colour additive.
  /// </summary>
  public static class SubstanceNameDomainCodes
  {
    /// <summary>
    /// Active Ingredient
    /// </summary>
    public static readonly Coding ActiveIngredient = new Coding
    {
      Code = "ActiveIngredient",
      Display = "Active Ingredient",
      System = "http://hl7.org/fhir/substance-name-domain"
    };
    /// <summary>
    /// Food Color Additive
    /// </summary>
    public static readonly Coding FoodColorAdditive = new Coding
    {
      Code = "FoodColorAdditive",
      Display = "Food Color Additive",
      System = "http://hl7.org/fhir/substance-name-domain"
    };

    /// <summary>
    /// Literal for code: ActiveIngredient
    /// </summary>
    public const string LiteralActiveIngredient = "ActiveIngredient";

    /// <summary>
    /// Literal for code: SubstanceNameDomainActiveIngredient
    /// </summary>
    public const string LiteralSubstanceNameDomainActiveIngredient = "http://hl7.org/fhir/substance-name-domain#ActiveIngredient";

    /// <summary>
    /// Literal for code: FoodColorAdditive
    /// </summary>
    public const string LiteralFoodColorAdditive = "FoodColorAdditive";

    /// <summary>
    /// Literal for code: SubstanceNameDomainFoodColorAdditive
    /// </summary>
    public const string LiteralSubstanceNameDomainFoodColorAdditive = "http://hl7.org/fhir/substance-name-domain#FoodColorAdditive";

    /// <summary>
    /// Dictionary for looking up SubstanceNameDomain Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "ActiveIngredient", ActiveIngredient }, 
      { "http://hl7.org/fhir/substance-name-domain#ActiveIngredient", ActiveIngredient }, 
      { "FoodColorAdditive", FoodColorAdditive }, 
      { "http://hl7.org/fhir/substance-name-domain#FoodColorAdditive", FoodColorAdditive }, 
    };
  };
}
