// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// This value set includes some method codes from SNOMED CT - provided as an exemplar
  /// </summary>
  public static class AdministrationMethodCodesCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoseFormAdministrationMethod = new Coding
    {
      Code = "736665006",
      Display = "Dose form administration method",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Administer = new Coding
    {
      Code = "738990001",
      Display = "Administer",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Apply = new Coding
    {
      Code = "738991002",
      Display = "Apply",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Chew = new Coding
    {
      Code = "738992009",
      Display = "Chew",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Insert = new Coding
    {
      Code = "738993004",
      Display = "Insert",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Instill = new Coding
    {
      Code = "738994005",
      Display = "Instill",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Swallow = new Coding
    {
      Code = "738995006",
      Display = "Swallow",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spray = new Coding
    {
      Code = "738996007",
      Display = "Spray",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Inhale = new Coding
    {
      Code = "740666001",
      Display = "Inhale",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Inject = new Coding
    {
      Code = "740685003",
      Display = "Inject",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Suck = new Coding
    {
      Code = "764498003",
      Display = "Suck",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Infuse = new Coding
    {
      Code = "764794000",
      Display = "Infuse",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rinse = new Coding
    {
      Code = "782155003",
      Display = "Rinse",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Gargle = new Coding
    {
      Code = "782168006",
      Display = "Gargle",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RinseOrWash = new Coding
    {
      Code = "785900008",
      Display = "Rinse or wash",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Orodisperse = new Coding
    {
      Code = "823034001",
      Display = "Orodisperse",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Implant = new Coding
    {
      Code = "827107003",
      Display = "Implant",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: DoseFormAdministrationMethod
    /// </summary>
    public const string LiteralDoseFormAdministrationMethod = "736665006";

    /// <summary>
    /// Literal for code: Administer
    /// </summary>
    public const string LiteralAdminister = "738990001";

    /// <summary>
    /// Literal for code: Apply
    /// </summary>
    public const string LiteralApply = "738991002";

    /// <summary>
    /// Literal for code: Chew
    /// </summary>
    public const string LiteralChew = "738992009";

    /// <summary>
    /// Literal for code: Insert
    /// </summary>
    public const string LiteralInsert = "738993004";

    /// <summary>
    /// Literal for code: Instill
    /// </summary>
    public const string LiteralInstill = "738994005";

    /// <summary>
    /// Literal for code: Swallow
    /// </summary>
    public const string LiteralSwallow = "738995006";

    /// <summary>
    /// Literal for code: Spray
    /// </summary>
    public const string LiteralSpray = "738996007";

    /// <summary>
    /// Literal for code: Inhale
    /// </summary>
    public const string LiteralInhale = "740666001";

    /// <summary>
    /// Literal for code: Inject
    /// </summary>
    public const string LiteralInject = "740685003";

    /// <summary>
    /// Literal for code: Suck
    /// </summary>
    public const string LiteralSuck = "764498003";

    /// <summary>
    /// Literal for code: Infuse
    /// </summary>
    public const string LiteralInfuse = "764794000";

    /// <summary>
    /// Literal for code: Rinse
    /// </summary>
    public const string LiteralRinse = "782155003";

    /// <summary>
    /// Literal for code: Gargle
    /// </summary>
    public const string LiteralGargle = "782168006";

    /// <summary>
    /// Literal for code: RinseOrWash
    /// </summary>
    public const string LiteralRinseOrWash = "785900008";

    /// <summary>
    /// Literal for code: Orodisperse
    /// </summary>
    public const string LiteralOrodisperse = "823034001";

    /// <summary>
    /// Literal for code: Implant
    /// </summary>
    public const string LiteralImplant = "827107003";
  };
}
