// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The type of artifact comment (documentation, review, guidance)
  /// </summary>
  public static class ArtifactCommentTypeCodes
  {
    /// <summary>
    /// The comment is providing additional documentation from an authoring perspective
    /// </summary>
    public static readonly Coding Documentation = new Coding
    {
      Code = "documentation",
      Display = "Documentation",
      System = "http://hl7.org/fhir/CodeSystem/artifact-comment-type"
    };
    /// <summary>
    /// The comment is providing usage guidance to an artifact consumer
    /// </summary>
    public static readonly Coding Guidance = new Coding
    {
      Code = "guidance",
      Display = "Guidance",
      System = "http://hl7.org/fhir/CodeSystem/artifact-comment-type"
    };
    /// <summary>
    /// The comment is providing feedback from a reviewer and requires resolution
    /// </summary>
    public static readonly Coding Review = new Coding
    {
      Code = "review",
      Display = "Review",
      System = "http://hl7.org/fhir/CodeSystem/artifact-comment-type"
    };

    /// <summary>
    /// Literal for code: Documentation
    /// </summary>
    public const string LiteralDocumentation = "documentation";

    /// <summary>
    /// Literal for code: Guidance
    /// </summary>
    public const string LiteralGuidance = "guidance";

    /// <summary>
    /// Literal for code: Review
    /// </summary>
    public const string LiteralReview = "review";
  };
}
