// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Types of resources that can be attached to catalog entries.
  /// </summary>
  public static class CatalogentryTypeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ActivityDefinition = new Coding
    {
      Code = "ActivityDefinition",
      Display = "ActivityDefinition",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeviceDefinition = new Coding
    {
      Code = "DeviceDefinition",
      Display = "DeviceDefinition",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HealthcareService = new Coding
    {
      Code = "HealthcareService",
      Display = "HealthcareService",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Location = new Coding
    {
      Code = "Location",
      Display = "Location",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Medication = new Coding
    {
      Code = "Medication",
      Display = "Medication",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MedicationKnowledge = new Coding
    {
      Code = "MedicationKnowledge",
      Display = "MedicationKnowledge",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ObservationDefinition = new Coding
    {
      Code = "ObservationDefinition",
      Display = "ObservationDefinition",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Organization = new Coding
    {
      Code = "Organization",
      Display = "Organization",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PlanDefinition = new Coding
    {
      Code = "PlanDefinition",
      Display = "PlanDefinition",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Practitioner = new Coding
    {
      Code = "Practitioner",
      Display = "Practitioner",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PractitionerRole = new Coding
    {
      Code = "PractitionerRole",
      Display = "PractitionerRole",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpecimenDefinition = new Coding
    {
      Code = "SpecimenDefinition",
      Display = "SpecimenDefinition",
      System = "http://hl7.org/fhir/catalogentry-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Substance = new Coding
    {
      Code = "Substance",
      Display = "Substance",
      System = "http://hl7.org/fhir/catalogentry-type"
    };

    /// <summary>
    /// Literal for code: ActivityDefinition
    /// </summary>
    public const string LiteralActivityDefinition = "ActivityDefinition";

    /// <summary>
    /// Literal for code: DeviceDefinition
    /// </summary>
    public const string LiteralDeviceDefinition = "DeviceDefinition";

    /// <summary>
    /// Literal for code: HealthcareService
    /// </summary>
    public const string LiteralHealthcareService = "HealthcareService";

    /// <summary>
    /// Literal for code: Location
    /// </summary>
    public const string LiteralLocation = "Location";

    /// <summary>
    /// Literal for code: Medication
    /// </summary>
    public const string LiteralMedication = "Medication";

    /// <summary>
    /// Literal for code: MedicationKnowledge
    /// </summary>
    public const string LiteralMedicationKnowledge = "MedicationKnowledge";

    /// <summary>
    /// Literal for code: ObservationDefinition
    /// </summary>
    public const string LiteralObservationDefinition = "ObservationDefinition";

    /// <summary>
    /// Literal for code: Organization
    /// </summary>
    public const string LiteralOrganization = "Organization";

    /// <summary>
    /// Literal for code: PlanDefinition
    /// </summary>
    public const string LiteralPlanDefinition = "PlanDefinition";

    /// <summary>
    /// Literal for code: Practitioner
    /// </summary>
    public const string LiteralPractitioner = "Practitioner";

    /// <summary>
    /// Literal for code: PractitionerRole
    /// </summary>
    public const string LiteralPractitionerRole = "PractitionerRole";

    /// <summary>
    /// Literal for code: SpecimenDefinition
    /// </summary>
    public const string LiteralSpecimenDefinition = "SpecimenDefinition";

    /// <summary>
    /// Literal for code: Substance
    /// </summary>
    public const string LiteralSubstance = "Substance";
  };
}
