// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class ChoiceListOrientationCodes
  {
    /// <summary>
    /// List choices along the horizontal axis.
    /// </summary>
    public static readonly Coding Horizontal = new Coding
    {
      Code = "horizontal",
      Display = "Horizontal",
      System = "http://hl7.org/fhir/choice-list-orientation"
    };
    /// <summary>
    /// List choices down the vertical axis.
    /// </summary>
    public static readonly Coding Vertical = new Coding
    {
      Code = "vertical",
      Display = "Vertical",
      System = "http://hl7.org/fhir/choice-list-orientation"
    };

    /// <summary>
    /// Literal for code: Horizontal
    /// </summary>
    public const string LiteralHorizontal = "horizontal";

    /// <summary>
    /// Literal for code: Vertical
    /// </summary>
    public const string LiteralVertical = "vertical";
  };
}
