// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class ConceptSubsumptionOutcomeCodes
  {
    /// <summary>
    /// The two concepts are equivalent (have the same properties).
    /// </summary>
    public static readonly Coding Equivalent = new Coding
    {
      Code = "equivalent",
      Display = "Equivalent",
      System = "http://hl7.org/fhir/concept-subsumption-outcome"
    };
    /// <summary>
    /// Coding/code "A" and Coding/code "B" are disjoint (e.g. each has propeties that the other doesn't have).
    /// </summary>
    public static readonly Coding NotSubsumed = new Coding
    {
      Code = "not-subsumed",
      Display = "Not-Subsumed",
      System = "http://hl7.org/fhir/concept-subsumption-outcome"
    };
    /// <summary>
    /// Coding/code "A" is subsumed by Coding/code "B" (e.g. A has all the properties B has, and some of it's own).
    /// </summary>
    public static readonly Coding SubsumedBy = new Coding
    {
      Code = "subsumed-by",
      Display = "Subsumed-By",
      System = "http://hl7.org/fhir/concept-subsumption-outcome"
    };
    /// <summary>
    /// Coding/code "A" subsumes Coding/code "B" (e.g. B has all the properties A has, and some of it's own).
    /// </summary>
    public static readonly Coding Subsumes = new Coding
    {
      Code = "subsumes",
      Display = "Subsumes",
      System = "http://hl7.org/fhir/concept-subsumption-outcome"
    };

    /// <summary>
    /// Literal for code: Equivalent
    /// </summary>
    public const string LiteralEquivalent = "equivalent";

    /// <summary>
    /// Literal for code: NotSubsumed
    /// </summary>
    public const string LiteralNotSubsumed = "not-subsumed";

    /// <summary>
    /// Literal for code: SubsumedBy
    /// </summary>
    public const string LiteralSubsumedBy = "subsumed-by";

    /// <summary>
    /// Literal for code: Subsumes
    /// </summary>
    public const string LiteralSubsumes = "subsumes";
  };
}
