// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class ConformanceExpectationCodes
  {
    /// <summary>
    /// Support for the specified capability is not necessary to be considered conformant, and the requirement should be considered strictly optional.
    /// </summary>
    public static readonly Coding MAY = new Coding
    {
      Code = "MAY",
      Display = "MAY",
      System = "http://hl7.org/fhir/conformance-expectation"
    };
    /// <summary>
    /// Support for the specified capability is required to be considered conformant.
    /// </summary>
    public static readonly Coding SHALL = new Coding
    {
      Code = "SHALL",
      Display = "SHALL",
      System = "http://hl7.org/fhir/conformance-expectation"
    };
    /// <summary>
    /// Support for the specified capability is strongly encouraged, and failure to support it should only occur after careful consideration.
    /// </summary>
    public static readonly Coding SHOULD = new Coding
    {
      Code = "SHOULD",
      Display = "SHOULD",
      System = "http://hl7.org/fhir/conformance-expectation"
    };
    /// <summary>
    /// Support for the specified capability is strongly discouraged and should occur only after careful consideration.
    /// </summary>
    public static readonly Coding SHOULDNOT = new Coding
    {
      Code = "SHOULD-NOT",
      Display = "SHOULD-NOT",
      System = "http://hl7.org/fhir/conformance-expectation"
    };

    /// <summary>
    /// Literal for code: MAY
    /// </summary>
    public const string LiteralMAY = "MAY";

    /// <summary>
    /// Literal for code: SHALL
    /// </summary>
    public const string LiteralSHALL = "SHALL";

    /// <summary>
    /// Literal for code: SHOULD
    /// </summary>
    public const string LiteralSHOULD = "SHOULD";

    /// <summary>
    /// Literal for code: SHOULDNOT
    /// </summary>
    public const string LiteralSHOULDNOT = "SHOULD-NOT";
  };
}
