// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Used to code author list statement, contributorship statement, and such.
  /// </summary>
  public static class ContributorSummaryTypeCodes
  {
    /// <summary>
    /// Statement of acknowledgment of contributions beyond those compiled for formal contributorship statements.
    /// </summary>
    public static readonly Coding Acknowledgment = new Coding
    {
      Code = "acknowledgment",
      Display = "Acknowledgment",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-type"
    };
    /// <summary>
    /// Display of the author list as a complete string.
    /// </summary>
    public static readonly Coding AuthorString = new Coding
    {
      Code = "author-string",
      Display = "Author string",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-type"
    };
    /// <summary>
    /// Compiled summary of contributions.
    /// </summary>
    public static readonly Coding ContributorshipStatement = new Coding
    {
      Code = "contributorship-statement",
      Display = "Contributorship statement",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-type"
    };

    /// <summary>
    /// Literal for code: Acknowledgment
    /// </summary>
    public const string LiteralAcknowledgment = "acknowledgment";

    /// <summary>
    /// Literal for code: AuthorString
    /// </summary>
    public const string LiteralAuthorString = "author-string";

    /// <summary>
    /// Literal for code: ContributorshipStatement
    /// </summary>
    public const string LiteralContributorshipStatement = "contributorship-statement";
  };
}
