// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class ExpansionProcessingRuleCodes
  {
    /// <summary>
    /// The expansion (when in UI mode) includes all codes *and* any defined groups (in extensions).
    /// </summary>
    public static readonly Coding AllCodes = new Coding
    {
      Code = "all-codes",
      Display = "All Codes",
      System = "http://hl7.org/fhir/expansion-processing-rule"
    };
    /// <summary>
    /// The expansion (when in UI mode) only includes the defined groups.
    /// </summary>
    public static readonly Coding GroupsOnly = new Coding
    {
      Code = "groups-only",
      Display = "Groups Only",
      System = "http://hl7.org/fhir/expansion-processing-rule"
    };
    /// <summary>
    /// The expanion (when in UI mode) lists the groups, and then any codes that have not been included in a group.
    /// </summary>
    public static readonly Coding GroupsPlusUngroupedCodes = new Coding
    {
      Code = "ungrouped",
      Display = "Groups + Ungrouped codes",
      System = "http://hl7.org/fhir/expansion-processing-rule"
    };

    /// <summary>
    /// Literal for code: AllCodes
    /// </summary>
    public const string LiteralAllCodes = "all-codes";

    /// <summary>
    /// Literal for code: GroupsOnly
    /// </summary>
    public const string LiteralGroupsOnly = "groups-only";

    /// <summary>
    /// Literal for code: GroupsPlusUngroupedCodes
    /// </summary>
    public const string LiteralGroupsPlusUngroupedCodes = "ungrouped";
  };
}
