// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class ImplantStatusCodes
  {
    /// <summary>
    /// The implanted device has been turned off.
    /// </summary>
    public static readonly Coding Disabled = new Coding
    {
      Code = "disabled",
      Display = "Disabled",
      System = "http://hl7.org/fhir/implantStatus"
    };
    /// <summary>
    /// The implanted device is working normally.
    /// </summary>
    public static readonly Coding Functional = new Coding
    {
      Code = "functional",
      Display = "Functional",
      System = "http://hl7.org/fhir/implantStatus"
    };
    /// <summary>
    /// The implanted device is not working.
    /// </summary>
    public static readonly Coding NonFunctional = new Coding
    {
      Code = "non-functional",
      Display = "Non-Functional",
      System = "http://hl7.org/fhir/implantStatus"
    };
    /// <summary>
    /// the functional status of the implant has not been determined.
    /// </summary>
    public static readonly Coding Unknown = new Coding
    {
      Code = "unknown",
      Display = "Unknown",
      System = "http://hl7.org/fhir/implantStatus"
    };

    /// <summary>
    /// Literal for code: Disabled
    /// </summary>
    public const string LiteralDisabled = "disabled";

    /// <summary>
    /// Literal for code: Functional
    /// </summary>
    public const string LiteralFunctional = "functional";

    /// <summary>
    /// Literal for code: NonFunctional
    /// </summary>
    public const string LiteralNonFunctional = "non-functional";

    /// <summary>
    /// Literal for code: Unknown
    /// </summary>
    public const string LiteralUnknown = "unknown";
  };
}
