// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// A capability afforded by a knowledge artifact, e.g. shareable, computable, publishable, executable
  /// </summary>
  public static class KnowledgeCapabilityCodes
  {
    /// <summary>
    /// The artifact provides at least machine-readable capability (i.e. it does not _only_ have narrative or unstructured elements). This capability can also be characterized as the artifact provides design-time capability, for example, an artifact is computable if it contains semantically verified CQL logic.
    /// </summary>
    public static readonly Coding Computable = new Coding
    {
      Code = "computable",
      Display = "Computable",
      System = "http://hl7.org/fhir/CodeSystem/knowledge-capability"
    };
    /// <summary>
    /// The artifact is guaranteed to have the elements required to support execution of at least one run-time operation appropriate for the type of artifact. This capability can also be characterized as the artifact provides run-time capability, for example, an artifact is executable if it contains compiled ELM logic.
    /// </summary>
    public static readonly Coding Executable = new Coding
    {
      Code = "executable",
      Display = "Executable",
      System = "http://hl7.org/fhir/CodeSystem/knowledge-capability"
    };
    /// <summary>
    /// The artifact provides information necessary to provide content management capability, including dependency management, artifact lifecycle, and publishing and repository metadata.
    /// </summary>
    public static readonly Coding Publishable = new Coding
    {
      Code = "publishable",
      Display = "Publishable",
      System = "http://hl7.org/fhir/CodeSystem/knowledge-capability"
    };
    /// <summary>
    /// The artifact provides essential information necessary to ensure shareability of the content as a FHIR resource.
    /// </summary>
    public static readonly Coding Shareable = new Coding
    {
      Code = "shareable",
      Display = "Shareable",
      System = "http://hl7.org/fhir/CodeSystem/knowledge-capability"
    };

    /// <summary>
    /// Literal for code: Computable
    /// </summary>
    public const string LiteralComputable = "computable";

    /// <summary>
    /// Literal for code: Executable
    /// </summary>
    public const string LiteralExecutable = "executable";

    /// <summary>
    /// Literal for code: Publishable
    /// </summary>
    public const string LiteralPublishable = "publishable";

    /// <summary>
    /// Literal for code: Shareable
    /// </summary>
    public const string LiteralShareable = "shareable";
  };
}
