// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Medication Dose Aids
  /// </summary>
  public static class MedicationDoseAidCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BlisterPack = new Coding
    {
      Code = "blisterpack",
      Display = "Blister Pack",
      System = "http://hl7.org/fhir/CodeSystem/medication-dose-aid"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Dosette = new Coding
    {
      Code = "dosette",
      Display = "Dosette",
      System = "http://hl7.org/fhir/CodeSystem/medication-dose-aid"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Sachets = new Coding
    {
      Code = "sachets",
      Display = "Sachets",
      System = "http://hl7.org/fhir/CodeSystem/medication-dose-aid"
    };

    /// <summary>
    /// Literal for code: BlisterPack
    /// </summary>
    public const string LiteralBlisterPack = "blisterpack";

    /// <summary>
    /// Literal for code: Dosette
    /// </summary>
    public const string LiteralDosette = "dosette";

    /// <summary>
    /// Literal for code: Sachets
    /// </summary>
    public const string LiteralSachets = "sachets";
  };
}
