// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// This value set includes all unit of presentation codes from SNOMED CT - provided as an exemplar.
  /// </summary>
  public static class MedicationknowledgePackageTypeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UnitOfPresentation = new Coding
    {
      Code = "732935002",
      Display = "Unit of presentation",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tablet = new Coding
    {
      Code = "732936001",
      Display = "Tablet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Capsule = new Coding
    {
      Code = "732937005",
      Display = "Capsule",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Ampule = new Coding
    {
      Code = "732978007",
      Display = "Ampule",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Applicator = new Coding
    {
      Code = "732980001",
      Display = "Applicator",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Actuation = new Coding
    {
      Code = "732981002",
      Display = "Actuation",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Bag = new Coding
    {
      Code = "732982009",
      Display = "Bag",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Barrel = new Coding
    {
      Code = "732983004",
      Display = "Barrel",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Blister = new Coding
    {
      Code = "732984005",
      Display = "Blister",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Block = new Coding
    {
      Code = "732985006",
      Display = "Block",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Bottle = new Coding
    {
      Code = "732986007",
      Display = "Bottle",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cachet = new Coding
    {
      Code = "732987003",
      Display = "Cachet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cartridge = new Coding
    {
      Code = "732988008",
      Display = "Cartridge",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChewingGum = new Coding
    {
      Code = "732989000",
      Display = "Chewing gum",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Container = new Coding
    {
      Code = "732990009",
      Display = "Container",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cup = new Coding
    {
      Code = "732991008",
      Display = "Cup",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cylinder = new Coding
    {
      Code = "732992001",
      Display = "Cylinder",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Dressing = new Coding
    {
      Code = "732993006",
      Display = "Dressing",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Drop = new Coding
    {
      Code = "732994000",
      Display = "Drop",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Film = new Coding
    {
      Code = "732995004",
      Display = "Film",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Implant = new Coding
    {
      Code = "732996003",
      Display = "Implant",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Inhaler = new Coding
    {
      Code = "732997007",
      Display = "Inhaler",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Insert = new Coding
    {
      Code = "732998002",
      Display = "Insert",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Jar = new Coding
    {
      Code = "732999005",
      Display = "Jar",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Lozenge = new Coding
    {
      Code = "733000006",
      Display = "Lozenge",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Lyophilisate = new Coding
    {
      Code = "733001005",
      Display = "Lyophilisate",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Matrix = new Coding
    {
      Code = "733002003",
      Display = "Matrix",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pad = new Coding
    {
      Code = "733003008",
      Display = "Pad",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pastille = new Coding
    {
      Code = "733004002",
      Display = "Pastille",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Patch = new Coding
    {
      Code = "733005001",
      Display = "Patch",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pen = new Coding
    {
      Code = "733006000",
      Display = "Pen",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pessary = new Coding
    {
      Code = "733007009",
      Display = "Pessary",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pillule = new Coding
    {
      Code = "733008004",
      Display = "Pillule",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pipette = new Coding
    {
      Code = "733009007",
      Display = "Pipette",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Plaster = new Coding
    {
      Code = "733010002",
      Display = "Plaster",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Plug = new Coding
    {
      Code = "733011003",
      Display = "Plug",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pouch = new Coding
    {
      Code = "733012005",
      Display = "Pouch",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Sachet = new Coding
    {
      Code = "733013000",
      Display = "Sachet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Sponge = new Coding
    {
      Code = "733014006",
      Display = "Sponge",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spoonful = new Coding
    {
      Code = "733015007",
      Display = "Spoonful",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Stick = new Coding
    {
      Code = "733016008",
      Display = "Stick",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Straw = new Coding
    {
      Code = "733017004",
      Display = "Straw",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Strip = new Coding
    {
      Code = "733018009",
      Display = "Strip",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Suppository = new Coding
    {
      Code = "733019001",
      Display = "Suppository",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Syringe = new Coding
    {
      Code = "733020007",
      Display = "Syringe",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding System = new Coding
    {
      Code = "733021006",
      Display = "System",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tampon = new Coding
    {
      Code = "733022004",
      Display = "Tampon",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Thread = new Coding
    {
      Code = "733023009",
      Display = "Thread",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tube = new Coding
    {
      Code = "733024003",
      Display = "Tube",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Vessel = new Coding
    {
      Code = "733025002",
      Display = "Vessel",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Vial = new Coding
    {
      Code = "733026001",
      Display = "Vial",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: UnitOfPresentation
    /// </summary>
    public const string LiteralUnitOfPresentation = "732935002";

    /// <summary>
    /// Literal for code: Tablet
    /// </summary>
    public const string LiteralTablet = "732936001";

    /// <summary>
    /// Literal for code: Capsule
    /// </summary>
    public const string LiteralCapsule = "732937005";

    /// <summary>
    /// Literal for code: Ampule
    /// </summary>
    public const string LiteralAmpule = "732978007";

    /// <summary>
    /// Literal for code: Applicator
    /// </summary>
    public const string LiteralApplicator = "732980001";

    /// <summary>
    /// Literal for code: Actuation
    /// </summary>
    public const string LiteralActuation = "732981002";

    /// <summary>
    /// Literal for code: Bag
    /// </summary>
    public const string LiteralBag = "732982009";

    /// <summary>
    /// Literal for code: Barrel
    /// </summary>
    public const string LiteralBarrel = "732983004";

    /// <summary>
    /// Literal for code: Blister
    /// </summary>
    public const string LiteralBlister = "732984005";

    /// <summary>
    /// Literal for code: Block
    /// </summary>
    public const string LiteralBlock = "732985006";

    /// <summary>
    /// Literal for code: Bottle
    /// </summary>
    public const string LiteralBottle = "732986007";

    /// <summary>
    /// Literal for code: Cachet
    /// </summary>
    public const string LiteralCachet = "732987003";

    /// <summary>
    /// Literal for code: Cartridge
    /// </summary>
    public const string LiteralCartridge = "732988008";

    /// <summary>
    /// Literal for code: ChewingGum
    /// </summary>
    public const string LiteralChewingGum = "732989000";

    /// <summary>
    /// Literal for code: Container
    /// </summary>
    public const string LiteralContainer = "732990009";

    /// <summary>
    /// Literal for code: Cup
    /// </summary>
    public const string LiteralCup = "732991008";

    /// <summary>
    /// Literal for code: Cylinder
    /// </summary>
    public const string LiteralCylinder = "732992001";

    /// <summary>
    /// Literal for code: Dressing
    /// </summary>
    public const string LiteralDressing = "732993006";

    /// <summary>
    /// Literal for code: Drop
    /// </summary>
    public const string LiteralDrop = "732994000";

    /// <summary>
    /// Literal for code: Film
    /// </summary>
    public const string LiteralFilm = "732995004";

    /// <summary>
    /// Literal for code: Implant
    /// </summary>
    public const string LiteralImplant = "732996003";

    /// <summary>
    /// Literal for code: Inhaler
    /// </summary>
    public const string LiteralInhaler = "732997007";

    /// <summary>
    /// Literal for code: Insert
    /// </summary>
    public const string LiteralInsert = "732998002";

    /// <summary>
    /// Literal for code: Jar
    /// </summary>
    public const string LiteralJar = "732999005";

    /// <summary>
    /// Literal for code: Lozenge
    /// </summary>
    public const string LiteralLozenge = "733000006";

    /// <summary>
    /// Literal for code: Lyophilisate
    /// </summary>
    public const string LiteralLyophilisate = "733001005";

    /// <summary>
    /// Literal for code: Matrix
    /// </summary>
    public const string LiteralMatrix = "733002003";

    /// <summary>
    /// Literal for code: Pad
    /// </summary>
    public const string LiteralPad = "733003008";

    /// <summary>
    /// Literal for code: Pastille
    /// </summary>
    public const string LiteralPastille = "733004002";

    /// <summary>
    /// Literal for code: Patch
    /// </summary>
    public const string LiteralPatch = "733005001";

    /// <summary>
    /// Literal for code: Pen
    /// </summary>
    public const string LiteralPen = "733006000";

    /// <summary>
    /// Literal for code: Pessary
    /// </summary>
    public const string LiteralPessary = "733007009";

    /// <summary>
    /// Literal for code: Pillule
    /// </summary>
    public const string LiteralPillule = "733008004";

    /// <summary>
    /// Literal for code: Pipette
    /// </summary>
    public const string LiteralPipette = "733009007";

    /// <summary>
    /// Literal for code: Plaster
    /// </summary>
    public const string LiteralPlaster = "733010002";

    /// <summary>
    /// Literal for code: Plug
    /// </summary>
    public const string LiteralPlug = "733011003";

    /// <summary>
    /// Literal for code: Pouch
    /// </summary>
    public const string LiteralPouch = "733012005";

    /// <summary>
    /// Literal for code: Sachet
    /// </summary>
    public const string LiteralSachet = "733013000";

    /// <summary>
    /// Literal for code: Sponge
    /// </summary>
    public const string LiteralSponge = "733014006";

    /// <summary>
    /// Literal for code: Spoonful
    /// </summary>
    public const string LiteralSpoonful = "733015007";

    /// <summary>
    /// Literal for code: Stick
    /// </summary>
    public const string LiteralStick = "733016008";

    /// <summary>
    /// Literal for code: Straw
    /// </summary>
    public const string LiteralStraw = "733017004";

    /// <summary>
    /// Literal for code: Strip
    /// </summary>
    public const string LiteralStrip = "733018009";

    /// <summary>
    /// Literal for code: Suppository
    /// </summary>
    public const string LiteralSuppository = "733019001";

    /// <summary>
    /// Literal for code: Syringe
    /// </summary>
    public const string LiteralSyringe = "733020007";

    /// <summary>
    /// Literal for code: System
    /// </summary>
    public const string LiteralSystem = "733021006";

    /// <summary>
    /// Literal for code: Tampon
    /// </summary>
    public const string LiteralTampon = "733022004";

    /// <summary>
    /// Literal for code: Thread
    /// </summary>
    public const string LiteralThread = "733023009";

    /// <summary>
    /// Literal for code: Tube
    /// </summary>
    public const string LiteralTube = "733024003";

    /// <summary>
    /// Literal for code: Vessel
    /// </summary>
    public const string LiteralVessel = "733025002";

    /// <summary>
    /// Literal for code: Vial
    /// </summary>
    public const string LiteralVial = "733026001";
  };
}
