// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Description Needed Here
  /// </summary>
  public static class QuestionnaireUsageModeCodes
  {
    /// <summary>
    /// Render the item only when capturing data.
    /// </summary>
    public static readonly Coding CaptureOnly = new Coding
    {
      Code = "capture",
      Display = "Capture Only",
      System = "http://hl7.org/fhir/questionnaire-usage-mode"
    };
    /// <summary>
    /// Render the item regardless of usage mode.
    /// </summary>
    public static readonly Coding CaptureAndDisplay = new Coding
    {
      Code = "capture-display",
      Display = "Capture & Display",
      System = "http://hl7.org/fhir/questionnaire-usage-mode"
    };
    /// <summary>
    /// Render the item when capturing data or when displaying a completed form and the item has been answered (or has child items that have been answered).
    /// </summary>
    public static readonly Coding CaptureOrIfAnsweredDisplay = new Coding
    {
      Code = "capture-display-non-empty",
      Display = "Capture or, if answered, Display",
      System = "http://hl7.org/fhir/questionnaire-usage-mode"
    };
    /// <summary>
    /// Render the item only when displaying a completed form.
    /// </summary>
    public static readonly Coding DisplayOnly = new Coding
    {
      Code = "display",
      Display = "Display Only",
      System = "http://hl7.org/fhir/questionnaire-usage-mode"
    };
    /// <summary>
    /// Render the item only when displaying a completed form and the item has been answered (or has child items that have been answered).
    /// </summary>
    public static readonly Coding DisplayWhenAnswered = new Coding
    {
      Code = "display-non-empty",
      Display = "Display when Answered",
      System = "http://hl7.org/fhir/questionnaire-usage-mode"
    };

    /// <summary>
    /// Literal for code: CaptureOnly
    /// </summary>
    public const string LiteralCaptureOnly = "capture";

    /// <summary>
    /// Literal for code: CaptureAndDisplay
    /// </summary>
    public const string LiteralCaptureAndDisplay = "capture-display";

    /// <summary>
    /// Literal for code: CaptureOrIfAnsweredDisplay
    /// </summary>
    public const string LiteralCaptureOrIfAnsweredDisplay = "capture-display-non-empty";

    /// <summary>
    /// Literal for code: DisplayOnly
    /// </summary>
    public const string LiteralDisplayOnly = "display";

    /// <summary>
    /// Literal for code: DisplayWhenAnswered
    /// </summary>
    public const string LiteralDisplayWhenAnswered = "display-non-empty";
  };
}
