// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The type of process where the audit event originated from.
  /// </summary>
  public static class SecuritySourceTypeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UserDevice = new Coding
    {
      Code = "1",
      Display = "User Device",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DataInterface = new Coding
    {
      Code = "2",
      Display = "Data Interface",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WebServer = new Coding
    {
      Code = "3",
      Display = "Web Server",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ApplicationServer = new Coding
    {
      Code = "4",
      Display = "Application Server",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DatabaseServer = new Coding
    {
      Code = "5",
      Display = "Database Server",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SecurityServer = new Coding
    {
      Code = "6",
      Display = "Security Server",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NetworkDevice = new Coding
    {
      Code = "7",
      Display = "Network Device",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NetworkRouter = new Coding
    {
      Code = "8",
      Display = "Network Router",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Other = new Coding
    {
      Code = "9",
      Display = "Other",
      System = "http://terminology.hl7.org/CodeSystem/security-source-type"
    };

    /// <summary>
    /// Literal for code: UserDevice
    /// </summary>
    public const string LiteralUserDevice = "1";

    /// <summary>
    /// Literal for code: DataInterface
    /// </summary>
    public const string LiteralDataInterface = "2";

    /// <summary>
    /// Literal for code: WebServer
    /// </summary>
    public const string LiteralWebServer = "3";

    /// <summary>
    /// Literal for code: ApplicationServer
    /// </summary>
    public const string LiteralApplicationServer = "4";

    /// <summary>
    /// Literal for code: DatabaseServer
    /// </summary>
    public const string LiteralDatabaseServer = "5";

    /// <summary>
    /// Literal for code: SecurityServer
    /// </summary>
    public const string LiteralSecurityServer = "6";

    /// <summary>
    /// Literal for code: NetworkDevice
    /// </summary>
    public const string LiteralNetworkDevice = "7";

    /// <summary>
    /// Literal for code: NetworkRouter
    /// </summary>
    public const string LiteralNetworkRouter = "8";

    /// <summary>
    /// Literal for code: Other
    /// </summary>
    public const string LiteralOther = "9";
  };
}
