// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// UCUM units for recording body length measures such as height and head circumference
  /// </summary>
  public static class UcumBodylengthCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE = new Coding
    {
      Code = "[in_i]",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE_2 = new Coding
    {
      Code = "cm",
      System = "http://unitsofmeasure.org"
    };

    /// <summary>
    /// Literal for code: NONE
    /// </summary>
    public const string LiteralNONE = "[in_i]";

    /// <summary>
    /// Literal for code: NONE_2
    /// </summary>
    public const string LiteralNONE_2 = "cm";
  };
}
