// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// UCUM units for recording Body Temperature
  /// </summary>
  public static class UcumBodytempCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE = new Coding
    {
      Code = "[degF]",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE_2 = new Coding
    {
      Code = "Cel",
      System = "http://unitsofmeasure.org"
    };

    /// <summary>
    /// Literal for code: NONE
    /// </summary>
    public const string LiteralNONE = "[degF]";

    /// <summary>
    /// Literal for code: NONE_2
    /// </summary>
    public const string LiteralNONE_2 = "Cel";
  };
}
