// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// This identifies the vaccine substance administered - CVX codes.
  /// </summary>
  public static class VaccineCodeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTP = new Coding
    {
      Code = "01",
      Display = "DTP",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OPV = new Coding
    {
      Code = "02",
      Display = "OPV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MMR = new Coding
    {
      Code = "03",
      Display = "MMR",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MR = new Coding
    {
      Code = "04",
      Display = "M/R",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Measles = new Coding
    {
      Code = "05",
      Display = "measles",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rubella = new Coding
    {
      Code = "06",
      Display = "rubella",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Mumps = new Coding
    {
      Code = "07",
      Display = "mumps",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepBAdolescentOrPediatric = new Coding
    {
      Code = "08",
      Display = "Hep B, adolescent or pediatric",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TdAdult = new Coding
    {
      Code = "09",
      Display = "Td (adult)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IPV = new Coding
    {
      Code = "10",
      Display = "IPV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PneumococcalConjugate = new Coding
    {
      Code = "100",
      Display = "pneumococcal conjugate",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyphoidViCPs = new Coding
    {
      Code = "101",
      Display = "typhoid, ViCPs",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTPHibHepB = new Coding
    {
      Code = "102",
      Display = "DTP-Hib-Hep B",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MeningococcalCConjugate = new Coding
    {
      Code = "103",
      Display = "meningococcal C conjugate",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepAHepB = new Coding
    {
      Code = "104",
      Display = "Hep A-Hep B",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VacciniaSmallpoxDiluted = new Coding
    {
      Code = "105",
      Display = "vaccinia (smallpox) diluted",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaP5PertussisAntigens6 = new Coding
    {
      Code = "106",
      Display = "DTaP, 5 pertussis antigens6",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaPNOS = new Coding
    {
      Code = "107",
      Display = "DTaP, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MeningococcalNOS = new Coding
    {
      Code = "108",
      Display = "meningococcal, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PneumococcalNOS = new Coding
    {
      Code = "109",
      Display = "pneumococcal, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pertussis = new Coding
    {
      Code = "11",
      Display = "pertussis",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaPHepBIPV = new Coding
    {
      Code = "110",
      Display = "DTaP-Hep B-IPV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfluenzaLiveIntranasal = new Coding
    {
      Code = "111",
      Display = "influenza, live, intranasal",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TetanusToxoidNOS = new Coding
    {
      Code = "112",
      Display = "tetanus toxoid, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TdAdult_2 = new Coding
    {
      Code = "113",
      Display = "Td (adult)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MeningococcalACYW135DiphtheriaConjugate = new Coding
    {
      Code = "114",
      Display = "meningococcal A,C,Y,W-135 diphtheria conjugate",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tdap = new Coding
    {
      Code = "115",
      Display = "Tdap",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RotavirusPentavalent = new Coding
    {
      Code = "116",
      Display = "rotavirus, pentavalent",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VZIGIND = new Coding
    {
      Code = "117",
      Display = "VZIG (IND)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HPVBivalent = new Coding
    {
      Code = "118",
      Display = "HPV, bivalent",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RotavirusMonovalent = new Coding
    {
      Code = "119",
      Display = "rotavirus, monovalent",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiphtheriaAntitoxin = new Coding
    {
      Code = "12",
      Display = "diphtheria antitoxin",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaPHibIPV = new Coding
    {
      Code = "120",
      Display = "DTaP-Hib-IPV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Zoster = new Coding
    {
      Code = "121",
      Display = "zoster",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RotavirusNOS1 = new Coding
    {
      Code = "122",
      Display = "rotavirus, NOS1",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TIG = new Coding
    {
      Code = "13",
      Display = "TIG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IGNOS = new Coding
    {
      Code = "14",
      Display = "IG, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfluenzaSplitInclPurifiedSurfaceAntigen = new Coding
    {
      Code = "15",
      Display = "influenza, split (incl. purified surface antigen)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfluenzaWhole = new Coding
    {
      Code = "16",
      Display = "influenza, whole",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibNOS = new Coding
    {
      Code = "17",
      Display = "Hib, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RabiesIntramuscularInjection = new Coding
    {
      Code = "18",
      Display = "rabies, intramuscular injection",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BCG = new Coding
    {
      Code = "19",
      Display = "BCG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaP = new Coding
    {
      Code = "20",
      Display = "DTaP",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Varicella = new Coding
    {
      Code = "21",
      Display = "varicella",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTPHib = new Coding
    {
      Code = "22",
      Display = "DTP-Hib",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Plague = new Coding
    {
      Code = "23",
      Display = "plague",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Anthrax = new Coding
    {
      Code = "24",
      Display = "anthrax",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyphoidOral = new Coding
    {
      Code = "25",
      Display = "typhoid, oral",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cholera = new Coding
    {
      Code = "26",
      Display = "cholera",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BotulinumAntitoxin = new Coding
    {
      Code = "27",
      Display = "botulinum antitoxin",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTPediatric = new Coding
    {
      Code = "28",
      Display = "DT (pediatric)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CMVIG = new Coding
    {
      Code = "29",
      Display = "CMVIG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HBIG = new Coding
    {
      Code = "30",
      Display = "HBIG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepAPediatricNOS = new Coding
    {
      Code = "31",
      Display = "Hep A, pediatric, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Meningococcal = new Coding
    {
      Code = "32",
      Display = "meningococcal",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pneumococcal = new Coding
    {
      Code = "33",
      Display = "pneumococcal",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RIG = new Coding
    {
      Code = "34",
      Display = "RIG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TetanusToxoid = new Coding
    {
      Code = "35",
      Display = "tetanus toxoid",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VZIG = new Coding
    {
      Code = "36",
      Display = "VZIG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding YellowFever = new Coding
    {
      Code = "37",
      Display = "yellow fever",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RubellaMumps = new Coding
    {
      Code = "38",
      Display = "rubella/mumps",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding JapaneseEncephalitis = new Coding
    {
      Code = "39",
      Display = "Japanese encephalitis",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RabiesIntradermalInjection = new Coding
    {
      Code = "40",
      Display = "rabies, intradermal injection",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyphoidParenteral = new Coding
    {
      Code = "41",
      Display = "typhoid, parenteral",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepBAdolescentHighRiskInfant2 = new Coding
    {
      Code = "42",
      Display = "Hep B, adolescent/high risk infant2",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepBAdult4 = new Coding
    {
      Code = "43",
      Display = "Hep B, adult4",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepBDialysis = new Coding
    {
      Code = "44",
      Display = "Hep B, dialysis",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepBNOS = new Coding
    {
      Code = "45",
      Display = "Hep B, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibPRPD = new Coding
    {
      Code = "46",
      Display = "Hib (PRP-D)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibHbOC = new Coding
    {
      Code = "47",
      Display = "Hib (HbOC)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibPRPT = new Coding
    {
      Code = "48",
      Display = "Hib (PRP-T)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibPRPOMP = new Coding
    {
      Code = "49",
      Display = "Hib (PRP-OMP)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTaPHib = new Coding
    {
      Code = "50",
      Display = "DTaP-Hib",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibHepB = new Coding
    {
      Code = "51",
      Display = "Hib-Hep B",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepAAdult = new Coding
    {
      Code = "52",
      Display = "Hep A, adult",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyphoidParenteralAKDUSMilitary = new Coding
    {
      Code = "53",
      Display = "typhoid, parenteral, AKD (U.S. military)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdenovirusType4 = new Coding
    {
      Code = "54",
      Display = "adenovirus, type 4",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdenovirusType7 = new Coding
    {
      Code = "55",
      Display = "adenovirus, type 7",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DengueFever = new Coding
    {
      Code = "56",
      Display = "dengue fever",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Hantavirus = new Coding
    {
      Code = "57",
      Display = "hantavirus",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepC = new Coding
    {
      Code = "58",
      Display = "Hep C",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepE = new Coding
    {
      Code = "59",
      Display = "Hep E",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HerpesSimplex2 = new Coding
    {
      Code = "60",
      Display = "herpes simplex 2",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HIV = new Coding
    {
      Code = "61",
      Display = "HIV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HPVQuadrivalent = new Coding
    {
      Code = "62",
      Display = "HPV, quadrivalent",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding JuninVirus = new Coding
    {
      Code = "63",
      Display = "Junin virus",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Leishmaniasis = new Coding
    {
      Code = "64",
      Display = "leishmaniasis",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Leprosy = new Coding
    {
      Code = "65",
      Display = "leprosy",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LymeDisease = new Coding
    {
      Code = "66",
      Display = "Lyme disease",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Malaria = new Coding
    {
      Code = "67",
      Display = "malaria",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Melanoma = new Coding
    {
      Code = "68",
      Display = "melanoma",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Parainfluenza3 = new Coding
    {
      Code = "69",
      Display = "parainfluenza-3",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding QFever = new Coding
    {
      Code = "70",
      Display = "Q fever",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RSVIGIV = new Coding
    {
      Code = "71",
      Display = "RSV-IGIV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RheumaticFever = new Coding
    {
      Code = "72",
      Display = "rheumatic fever",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RiftValleyFever = new Coding
    {
      Code = "73",
      Display = "Rift Valley fever",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RotavirusTetravalent = new Coding
    {
      Code = "74",
      Display = "rotavirus, tetravalent",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VacciniaSmallpox = new Coding
    {
      Code = "75",
      Display = "vaccinia (smallpox)",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding StaphylococcusBacterioLysate = new Coding
    {
      Code = "76",
      Display = "Staphylococcus bacterio lysate",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TickBorneEncephalitis = new Coding
    {
      Code = "77",
      Display = "tick-borne encephalitis",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TularemiaVaccine = new Coding
    {
      Code = "78",
      Display = "tularemia vaccine",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VacciniaImmuneGlobulin = new Coding
    {
      Code = "79",
      Display = "vaccinia immune globulin",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VEELive = new Coding
    {
      Code = "80",
      Display = "VEE, live",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VEEInactivated = new Coding
    {
      Code = "81",
      Display = "VEE, inactivated",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdenovirusNOS1 = new Coding
    {
      Code = "82",
      Display = "adenovirus, NOS1",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepAPedAdol2Dose = new Coding
    {
      Code = "83",
      Display = "Hep A, ped/adol, 2 dose",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepAPedAdol3Dose = new Coding
    {
      Code = "84",
      Display = "Hep A, ped/adol, 3 dose",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepANOS = new Coding
    {
      Code = "85",
      Display = "Hep A, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IG = new Coding
    {
      Code = "86",
      Display = "IG",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IGIV = new Coding
    {
      Code = "87",
      Display = "IGIV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfluenzaNOS = new Coding
    {
      Code = "88",
      Display = "influenza, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PolioNOS = new Coding
    {
      Code = "89",
      Display = "polio, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RabiesNOS = new Coding
    {
      Code = "90",
      Display = "rabies, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyphoidNOS = new Coding
    {
      Code = "91",
      Display = "typhoid, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VEENOS = new Coding
    {
      Code = "92",
      Display = "VEE, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RSVMAb = new Coding
    {
      Code = "93",
      Display = "RSV-MAb",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MMRV = new Coding
    {
      Code = "94",
      Display = "MMRV",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TSTOTTineTest = new Coding
    {
      Code = "95",
      Display = "TST-OT tine test",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TSTPPDIntradermal = new Coding
    {
      Code = "96",
      Display = "TST-PPD intradermal",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TSTPPDTineTest = new Coding
    {
      Code = "97",
      Display = "TST-PPD tine test",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TSTNOS = new Coding
    {
      Code = "98",
      Display = "TST, NOS",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RESERVEDDoNotUse3 = new Coding
    {
      Code = "99",
      Display = "RESERVED - do not use3",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NoVaccineAdministered5 = new Coding
    {
      Code = "998",
      Display = "no vaccine administered5",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Unknown = new Coding
    {
      Code = "999",
      Display = "unknown",
      System = "http://hl7.org/fhir/sid/cvx"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Agrippal = new Coding
    {
      Code = "AGRPAL",
      Display = "Agrippal",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Avaxim = new Coding
    {
      Code = "AVAXM",
      Display = "Avaxim",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BCG_2 = new Coding
    {
      Code = "BCG",
      Display = "BCG",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CDT = new Coding
    {
      Code = "CDT",
      Display = "CDT",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding COMVAX = new Coding
    {
      Code = "CMX",
      Display = "COMVAX",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TripleAntigen = new Coding
    {
      Code = "DTP",
      Display = "Triple Antigen",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DTPa = new Coding
    {
      Code = "DTPA",
      Display = "DTPa",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EngerixB = new Coding
    {
      Code = "ENGP",
      Display = "Engerix B",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Fluarix = new Coding
    {
      Code = "FLRIX",
      Display = "Fluarix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Fluvax = new Coding
    {
      Code = "FLUVAX",
      Display = "Fluvax",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Fluvirin = new Coding
    {
      Code = "FLVRN",
      Display = "Fluvirin",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FluvaxJunior = new Coding
    {
      Code = "FVXJNR",
      Display = "Fluvax Junior",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Diphtheria = new Coding
    {
      Code = "GNDIP",
      Display = "Diphtheria",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Influenza = new Coding
    {
      Code = "GNFLU",
      Display = "Influenza",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepatitisB = new Coding
    {
      Code = "GNHEP",
      Display = "Hepatitis B",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HIB = new Coding
    {
      Code = "GNHIB",
      Display = "HIB",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepatitisA = new Coding
    {
      Code = "GNHPA",
      Display = "Hepatitis A",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding JapaneseEncephalitis_2 = new Coding
    {
      Code = "GNJEN",
      Display = "Japanese Encephalitis",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Measles_2 = new Coding
    {
      Code = "GNMEA",
      Display = "Measles",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MeningococcalC = new Coding
    {
      Code = "GNMEN",
      Display = "Meningococcal C",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Mumps_2 = new Coding
    {
      Code = "GNMUM",
      Display = "Mumps",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pneumococcal_2 = new Coding
    {
      Code = "GNPNE",
      Display = "Pneumococcal",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Polio = new Coding
    {
      Code = "GNPOL",
      Display = "Polio",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rotavirus = new Coding
    {
      Code = "GNROX",
      Display = "Rotavirus",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rubella_2 = new Coding
    {
      Code = "GNRUB",
      Display = "Rubella",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tetanus = new Coding
    {
      Code = "GNTET",
      Display = "Tetanus",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Varicella_2 = new Coding
    {
      Code = "GNVAR",
      Display = "Varicella",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TwinrixJunior = new Coding
    {
      Code = "HATWNJ",
      Display = "Twinrix Junior",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VaqtaPaedAdol = new Coding
    {
      Code = "HAVAQ",
      Display = "Vaqta Paed/Adol",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HavrixJunior = new Coding
    {
      Code = "HAVJ",
      Display = "Havrix Junior",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HibTITER = new Coding
    {
      Code = "HBOC",
      Display = "HibTITER",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HBV = new Coding
    {
      Code = "HBV",
      Display = "HBV",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HBVAXII = new Coding
    {
      Code = "HBVP",
      Display = "HBVAX II",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Hiberix = new Coding
    {
      Code = "HBX",
      Display = "Hiberix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfanrixHexa = new Coding
    {
      Code = "IFHX",
      Display = "Infanrix Hexa",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfanrixIPV = new Coding
    {
      Code = "IFIP",
      Display = "Infanrix-IPV",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfanrixPenta = new Coding
    {
      Code = "IFPA",
      Display = "Infanrix Penta",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Infanrix = new Coding
    {
      Code = "IFX",
      Display = "Infanrix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfanrixHepB = new Coding
    {
      Code = "IFXB",
      Display = "InfanrixHepB",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Influvac = new Coding
    {
      Code = "INFLUV",
      Display = "Influvac",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IPOL = new Coding
    {
      Code = "IPV",
      Display = "IPOL",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding JEVAX = new Coding
    {
      Code = "JEVAX",
      Display = "JE-VAX",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Menjugate = new Coding
    {
      Code = "MENJUG",
      Display = "Menjugate",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Meningitec = new Coding
    {
      Code = "MENTEC",
      Display = "Meningitec",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Menomune = new Coding
    {
      Code = "MENUME",
      Display = "Menomune",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MencevaxACWY = new Coding
    {
      Code = "MENVAX",
      Display = "Mencevax ACWY",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MMR_2 = new Coding
    {
      Code = "MMR",
      Display = "MMR",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MMRII = new Coding
    {
      Code = "MMRCSL",
      Display = "MMR II",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Priorix = new Coding
    {
      Code = "MMRSKB",
      Display = "Priorix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Menitorix = new Coding
    {
      Code = "MNTRX",
      Display = "Menitorix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NeisVacC = new Coding
    {
      Code = "NEISVC",
      Display = "NeisVac-C",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Polio_2 = new Coding
    {
      Code = "OPV",
      Display = "Polio",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pertussis_2 = new Coding
    {
      Code = "P",
      Display = "Pertussis",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Panvax = new Coding
    {
      Code = "PANVAX",
      Display = "Panvax",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pediacel = new Coding
    {
      Code = "PDCL",
      Display = "Pediacel",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Poliacel = new Coding
    {
      Code = "PLCL",
      Display = "Poliacel",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Pneumovax = new Coding
    {
      Code = "PNEUMO",
      Display = "Pneumovax",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ProQuad = new Coding
    {
      Code = "PROQAD",
      Display = "ProQuad",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ProHIBit = new Coding
    {
      Code = "PRPD",
      Display = "ProHIBit",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PedvaxHIB = new Coding
    {
      Code = "PRPOMP",
      Display = "PedvaxHIB",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ActHIB = new Coding
    {
      Code = "PRPT",
      Display = "ActHIB",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Prevenar7 = new Coding
    {
      Code = "PRVNR",
      Display = "Prevenar 7",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Prevenar13 = new Coding
    {
      Code = "PRVTH",
      Display = "Prevenar 13",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PriorixTetra = new Coding
    {
      Code = "PRXTEX",
      Display = "Priorix-Tetra",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Quadracel = new Coding
    {
      Code = "QDCL",
      Display = "Quadracel",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rotarix = new Coding
    {
      Code = "ROTRIX",
      Display = "Rotarix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Rotateq = new Coding
    {
      Code = "ROTTEQ",
      Display = "Rotateq",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Synflorix = new Coding
    {
      Code = "SYNFLX",
      Display = "Synflorix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Tripacel = new Coding
    {
      Code = "TCL",
      Display = "Tripacel",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Vaxigrip = new Coding
    {
      Code = "VAXGRP",
      Display = "Vaxigrip",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VaxigripJunior = new Coding
    {
      Code = "VGRJNR",
      Display = "Vaxigrip Junior",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Varilrix = new Coding
    {
      Code = "VLRIX",
      Display = "Varilrix",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Varivax = new Coding
    {
      Code = "VRVAX",
      Display = "Varivax",
      System = "urn:oid:1.2.36.1.2001.1005.17"
    };

    /// <summary>
    /// Literal for code: DTP
    /// </summary>
    public const string LiteralDTP = "01";

    /// <summary>
    /// Literal for code: OPV
    /// </summary>
    public const string LiteralOPV = "02";

    /// <summary>
    /// Literal for code: MMR
    /// </summary>
    public const string LiteralMMR = "03";

    /// <summary>
    /// Literal for code: MR
    /// </summary>
    public const string LiteralMR = "04";

    /// <summary>
    /// Literal for code: Measles
    /// </summary>
    public const string LiteralMeasles = "05";

    /// <summary>
    /// Literal for code: Rubella
    /// </summary>
    public const string LiteralRubella = "06";

    /// <summary>
    /// Literal for code: Mumps
    /// </summary>
    public const string LiteralMumps = "07";

    /// <summary>
    /// Literal for code: HepBAdolescentOrPediatric
    /// </summary>
    public const string LiteralHepBAdolescentOrPediatric = "08";

    /// <summary>
    /// Literal for code: TdAdult
    /// </summary>
    public const string LiteralTdAdult = "09";

    /// <summary>
    /// Literal for code: IPV
    /// </summary>
    public const string LiteralIPV = "10";

    /// <summary>
    /// Literal for code: PneumococcalConjugate
    /// </summary>
    public const string LiteralPneumococcalConjugate = "100";

    /// <summary>
    /// Literal for code: TyphoidViCPs
    /// </summary>
    public const string LiteralTyphoidViCPs = "101";

    /// <summary>
    /// Literal for code: DTPHibHepB
    /// </summary>
    public const string LiteralDTPHibHepB = "102";

    /// <summary>
    /// Literal for code: MeningococcalCConjugate
    /// </summary>
    public const string LiteralMeningococcalCConjugate = "103";

    /// <summary>
    /// Literal for code: HepAHepB
    /// </summary>
    public const string LiteralHepAHepB = "104";

    /// <summary>
    /// Literal for code: VacciniaSmallpoxDiluted
    /// </summary>
    public const string LiteralVacciniaSmallpoxDiluted = "105";

    /// <summary>
    /// Literal for code: DTaP5PertussisAntigens6
    /// </summary>
    public const string LiteralDTaP5PertussisAntigens6 = "106";

    /// <summary>
    /// Literal for code: DTaPNOS
    /// </summary>
    public const string LiteralDTaPNOS = "107";

    /// <summary>
    /// Literal for code: MeningococcalNOS
    /// </summary>
    public const string LiteralMeningococcalNOS = "108";

    /// <summary>
    /// Literal for code: PneumococcalNOS
    /// </summary>
    public const string LiteralPneumococcalNOS = "109";

    /// <summary>
    /// Literal for code: Pertussis
    /// </summary>
    public const string LiteralPertussis = "11";

    /// <summary>
    /// Literal for code: DTaPHepBIPV
    /// </summary>
    public const string LiteralDTaPHepBIPV = "110";

    /// <summary>
    /// Literal for code: InfluenzaLiveIntranasal
    /// </summary>
    public const string LiteralInfluenzaLiveIntranasal = "111";

    /// <summary>
    /// Literal for code: TetanusToxoidNOS
    /// </summary>
    public const string LiteralTetanusToxoidNOS = "112";

    /// <summary>
    /// Literal for code: TdAdult_2
    /// </summary>
    public const string LiteralTdAdult_2 = "113";

    /// <summary>
    /// Literal for code: MeningococcalACYW135DiphtheriaConjugate
    /// </summary>
    public const string LiteralMeningococcalACYW135DiphtheriaConjugate = "114";

    /// <summary>
    /// Literal for code: Tdap
    /// </summary>
    public const string LiteralTdap = "115";

    /// <summary>
    /// Literal for code: RotavirusPentavalent
    /// </summary>
    public const string LiteralRotavirusPentavalent = "116";

    /// <summary>
    /// Literal for code: VZIGIND
    /// </summary>
    public const string LiteralVZIGIND = "117";

    /// <summary>
    /// Literal for code: HPVBivalent
    /// </summary>
    public const string LiteralHPVBivalent = "118";

    /// <summary>
    /// Literal for code: RotavirusMonovalent
    /// </summary>
    public const string LiteralRotavirusMonovalent = "119";

    /// <summary>
    /// Literal for code: DiphtheriaAntitoxin
    /// </summary>
    public const string LiteralDiphtheriaAntitoxin = "12";

    /// <summary>
    /// Literal for code: DTaPHibIPV
    /// </summary>
    public const string LiteralDTaPHibIPV = "120";

    /// <summary>
    /// Literal for code: Zoster
    /// </summary>
    public const string LiteralZoster = "121";

    /// <summary>
    /// Literal for code: RotavirusNOS1
    /// </summary>
    public const string LiteralRotavirusNOS1 = "122";

    /// <summary>
    /// Literal for code: TIG
    /// </summary>
    public const string LiteralTIG = "13";

    /// <summary>
    /// Literal for code: IGNOS
    /// </summary>
    public const string LiteralIGNOS = "14";

    /// <summary>
    /// Literal for code: InfluenzaSplitInclPurifiedSurfaceAntigen
    /// </summary>
    public const string LiteralInfluenzaSplitInclPurifiedSurfaceAntigen = "15";

    /// <summary>
    /// Literal for code: InfluenzaWhole
    /// </summary>
    public const string LiteralInfluenzaWhole = "16";

    /// <summary>
    /// Literal for code: HibNOS
    /// </summary>
    public const string LiteralHibNOS = "17";

    /// <summary>
    /// Literal for code: RabiesIntramuscularInjection
    /// </summary>
    public const string LiteralRabiesIntramuscularInjection = "18";

    /// <summary>
    /// Literal for code: BCG
    /// </summary>
    public const string LiteralBCG = "19";

    /// <summary>
    /// Literal for code: DTaP
    /// </summary>
    public const string LiteralDTaP = "20";

    /// <summary>
    /// Literal for code: Varicella
    /// </summary>
    public const string LiteralVaricella = "21";

    /// <summary>
    /// Literal for code: DTPHib
    /// </summary>
    public const string LiteralDTPHib = "22";

    /// <summary>
    /// Literal for code: Plague
    /// </summary>
    public const string LiteralPlague = "23";

    /// <summary>
    /// Literal for code: Anthrax
    /// </summary>
    public const string LiteralAnthrax = "24";

    /// <summary>
    /// Literal for code: TyphoidOral
    /// </summary>
    public const string LiteralTyphoidOral = "25";

    /// <summary>
    /// Literal for code: Cholera
    /// </summary>
    public const string LiteralCholera = "26";

    /// <summary>
    /// Literal for code: BotulinumAntitoxin
    /// </summary>
    public const string LiteralBotulinumAntitoxin = "27";

    /// <summary>
    /// Literal for code: DTPediatric
    /// </summary>
    public const string LiteralDTPediatric = "28";

    /// <summary>
    /// Literal for code: CMVIG
    /// </summary>
    public const string LiteralCMVIG = "29";

    /// <summary>
    /// Literal for code: HBIG
    /// </summary>
    public const string LiteralHBIG = "30";

    /// <summary>
    /// Literal for code: HepAPediatricNOS
    /// </summary>
    public const string LiteralHepAPediatricNOS = "31";

    /// <summary>
    /// Literal for code: Meningococcal
    /// </summary>
    public const string LiteralMeningococcal = "32";

    /// <summary>
    /// Literal for code: Pneumococcal
    /// </summary>
    public const string LiteralPneumococcal = "33";

    /// <summary>
    /// Literal for code: RIG
    /// </summary>
    public const string LiteralRIG = "34";

    /// <summary>
    /// Literal for code: TetanusToxoid
    /// </summary>
    public const string LiteralTetanusToxoid = "35";

    /// <summary>
    /// Literal for code: VZIG
    /// </summary>
    public const string LiteralVZIG = "36";

    /// <summary>
    /// Literal for code: YellowFever
    /// </summary>
    public const string LiteralYellowFever = "37";

    /// <summary>
    /// Literal for code: RubellaMumps
    /// </summary>
    public const string LiteralRubellaMumps = "38";

    /// <summary>
    /// Literal for code: JapaneseEncephalitis
    /// </summary>
    public const string LiteralJapaneseEncephalitis = "39";

    /// <summary>
    /// Literal for code: RabiesIntradermalInjection
    /// </summary>
    public const string LiteralRabiesIntradermalInjection = "40";

    /// <summary>
    /// Literal for code: TyphoidParenteral
    /// </summary>
    public const string LiteralTyphoidParenteral = "41";

    /// <summary>
    /// Literal for code: HepBAdolescentHighRiskInfant2
    /// </summary>
    public const string LiteralHepBAdolescentHighRiskInfant2 = "42";

    /// <summary>
    /// Literal for code: HepBAdult4
    /// </summary>
    public const string LiteralHepBAdult4 = "43";

    /// <summary>
    /// Literal for code: HepBDialysis
    /// </summary>
    public const string LiteralHepBDialysis = "44";

    /// <summary>
    /// Literal for code: HepBNOS
    /// </summary>
    public const string LiteralHepBNOS = "45";

    /// <summary>
    /// Literal for code: HibPRPD
    /// </summary>
    public const string LiteralHibPRPD = "46";

    /// <summary>
    /// Literal for code: HibHbOC
    /// </summary>
    public const string LiteralHibHbOC = "47";

    /// <summary>
    /// Literal for code: HibPRPT
    /// </summary>
    public const string LiteralHibPRPT = "48";

    /// <summary>
    /// Literal for code: HibPRPOMP
    /// </summary>
    public const string LiteralHibPRPOMP = "49";

    /// <summary>
    /// Literal for code: DTaPHib
    /// </summary>
    public const string LiteralDTaPHib = "50";

    /// <summary>
    /// Literal for code: HibHepB
    /// </summary>
    public const string LiteralHibHepB = "51";

    /// <summary>
    /// Literal for code: HepAAdult
    /// </summary>
    public const string LiteralHepAAdult = "52";

    /// <summary>
    /// Literal for code: TyphoidParenteralAKDUSMilitary
    /// </summary>
    public const string LiteralTyphoidParenteralAKDUSMilitary = "53";

    /// <summary>
    /// Literal for code: AdenovirusType4
    /// </summary>
    public const string LiteralAdenovirusType4 = "54";

    /// <summary>
    /// Literal for code: AdenovirusType7
    /// </summary>
    public const string LiteralAdenovirusType7 = "55";

    /// <summary>
    /// Literal for code: DengueFever
    /// </summary>
    public const string LiteralDengueFever = "56";

    /// <summary>
    /// Literal for code: Hantavirus
    /// </summary>
    public const string LiteralHantavirus = "57";

    /// <summary>
    /// Literal for code: HepC
    /// </summary>
    public const string LiteralHepC = "58";

    /// <summary>
    /// Literal for code: HepE
    /// </summary>
    public const string LiteralHepE = "59";

    /// <summary>
    /// Literal for code: HerpesSimplex2
    /// </summary>
    public const string LiteralHerpesSimplex2 = "60";

    /// <summary>
    /// Literal for code: HIV
    /// </summary>
    public const string LiteralHIV = "61";

    /// <summary>
    /// Literal for code: HPVQuadrivalent
    /// </summary>
    public const string LiteralHPVQuadrivalent = "62";

    /// <summary>
    /// Literal for code: JuninVirus
    /// </summary>
    public const string LiteralJuninVirus = "63";

    /// <summary>
    /// Literal for code: Leishmaniasis
    /// </summary>
    public const string LiteralLeishmaniasis = "64";

    /// <summary>
    /// Literal for code: Leprosy
    /// </summary>
    public const string LiteralLeprosy = "65";

    /// <summary>
    /// Literal for code: LymeDisease
    /// </summary>
    public const string LiteralLymeDisease = "66";

    /// <summary>
    /// Literal for code: Malaria
    /// </summary>
    public const string LiteralMalaria = "67";

    /// <summary>
    /// Literal for code: Melanoma
    /// </summary>
    public const string LiteralMelanoma = "68";

    /// <summary>
    /// Literal for code: Parainfluenza3
    /// </summary>
    public const string LiteralParainfluenza3 = "69";

    /// <summary>
    /// Literal for code: QFever
    /// </summary>
    public const string LiteralQFever = "70";

    /// <summary>
    /// Literal for code: RSVIGIV
    /// </summary>
    public const string LiteralRSVIGIV = "71";

    /// <summary>
    /// Literal for code: RheumaticFever
    /// </summary>
    public const string LiteralRheumaticFever = "72";

    /// <summary>
    /// Literal for code: RiftValleyFever
    /// </summary>
    public const string LiteralRiftValleyFever = "73";

    /// <summary>
    /// Literal for code: RotavirusTetravalent
    /// </summary>
    public const string LiteralRotavirusTetravalent = "74";

    /// <summary>
    /// Literal for code: VacciniaSmallpox
    /// </summary>
    public const string LiteralVacciniaSmallpox = "75";

    /// <summary>
    /// Literal for code: StaphylococcusBacterioLysate
    /// </summary>
    public const string LiteralStaphylococcusBacterioLysate = "76";

    /// <summary>
    /// Literal for code: TickBorneEncephalitis
    /// </summary>
    public const string LiteralTickBorneEncephalitis = "77";

    /// <summary>
    /// Literal for code: TularemiaVaccine
    /// </summary>
    public const string LiteralTularemiaVaccine = "78";

    /// <summary>
    /// Literal for code: VacciniaImmuneGlobulin
    /// </summary>
    public const string LiteralVacciniaImmuneGlobulin = "79";

    /// <summary>
    /// Literal for code: VEELive
    /// </summary>
    public const string LiteralVEELive = "80";

    /// <summary>
    /// Literal for code: VEEInactivated
    /// </summary>
    public const string LiteralVEEInactivated = "81";

    /// <summary>
    /// Literal for code: AdenovirusNOS1
    /// </summary>
    public const string LiteralAdenovirusNOS1 = "82";

    /// <summary>
    /// Literal for code: HepAPedAdol2Dose
    /// </summary>
    public const string LiteralHepAPedAdol2Dose = "83";

    /// <summary>
    /// Literal for code: HepAPedAdol3Dose
    /// </summary>
    public const string LiteralHepAPedAdol3Dose = "84";

    /// <summary>
    /// Literal for code: HepANOS
    /// </summary>
    public const string LiteralHepANOS = "85";

    /// <summary>
    /// Literal for code: IG
    /// </summary>
    public const string LiteralIG = "86";

    /// <summary>
    /// Literal for code: IGIV
    /// </summary>
    public const string LiteralIGIV = "87";

    /// <summary>
    /// Literal for code: InfluenzaNOS
    /// </summary>
    public const string LiteralInfluenzaNOS = "88";

    /// <summary>
    /// Literal for code: PolioNOS
    /// </summary>
    public const string LiteralPolioNOS = "89";

    /// <summary>
    /// Literal for code: RabiesNOS
    /// </summary>
    public const string LiteralRabiesNOS = "90";

    /// <summary>
    /// Literal for code: TyphoidNOS
    /// </summary>
    public const string LiteralTyphoidNOS = "91";

    /// <summary>
    /// Literal for code: VEENOS
    /// </summary>
    public const string LiteralVEENOS = "92";

    /// <summary>
    /// Literal for code: RSVMAb
    /// </summary>
    public const string LiteralRSVMAb = "93";

    /// <summary>
    /// Literal for code: MMRV
    /// </summary>
    public const string LiteralMMRV = "94";

    /// <summary>
    /// Literal for code: TSTOTTineTest
    /// </summary>
    public const string LiteralTSTOTTineTest = "95";

    /// <summary>
    /// Literal for code: TSTPPDIntradermal
    /// </summary>
    public const string LiteralTSTPPDIntradermal = "96";

    /// <summary>
    /// Literal for code: TSTPPDTineTest
    /// </summary>
    public const string LiteralTSTPPDTineTest = "97";

    /// <summary>
    /// Literal for code: TSTNOS
    /// </summary>
    public const string LiteralTSTNOS = "98";

    /// <summary>
    /// Literal for code: RESERVEDDoNotUse3
    /// </summary>
    public const string LiteralRESERVEDDoNotUse3 = "99";

    /// <summary>
    /// Literal for code: NoVaccineAdministered5
    /// </summary>
    public const string LiteralNoVaccineAdministered5 = "998";

    /// <summary>
    /// Literal for code: Unknown
    /// </summary>
    public const string LiteralUnknown = "999";

    /// <summary>
    /// Literal for code: Agrippal
    /// </summary>
    public const string LiteralAgrippal = "AGRPAL";

    /// <summary>
    /// Literal for code: Avaxim
    /// </summary>
    public const string LiteralAvaxim = "AVAXM";

    /// <summary>
    /// Literal for code: BCG_2
    /// </summary>
    public const string LiteralBCG_2 = "BCG";

    /// <summary>
    /// Literal for code: CDT
    /// </summary>
    public const string LiteralCDT = "CDT";

    /// <summary>
    /// Literal for code: COMVAX
    /// </summary>
    public const string LiteralCOMVAX = "CMX";

    /// <summary>
    /// Literal for code: TripleAntigen
    /// </summary>
    public const string LiteralTripleAntigen = "DTP";

    /// <summary>
    /// Literal for code: DTPa
    /// </summary>
    public const string LiteralDTPa = "DTPA";

    /// <summary>
    /// Literal for code: EngerixB
    /// </summary>
    public const string LiteralEngerixB = "ENGP";

    /// <summary>
    /// Literal for code: Fluarix
    /// </summary>
    public const string LiteralFluarix = "FLRIX";

    /// <summary>
    /// Literal for code: Fluvax
    /// </summary>
    public const string LiteralFluvax = "FLUVAX";

    /// <summary>
    /// Literal for code: Fluvirin
    /// </summary>
    public const string LiteralFluvirin = "FLVRN";

    /// <summary>
    /// Literal for code: FluvaxJunior
    /// </summary>
    public const string LiteralFluvaxJunior = "FVXJNR";

    /// <summary>
    /// Literal for code: Diphtheria
    /// </summary>
    public const string LiteralDiphtheria = "GNDIP";

    /// <summary>
    /// Literal for code: Influenza
    /// </summary>
    public const string LiteralInfluenza = "GNFLU";

    /// <summary>
    /// Literal for code: HepatitisB
    /// </summary>
    public const string LiteralHepatitisB = "GNHEP";

    /// <summary>
    /// Literal for code: HIB
    /// </summary>
    public const string LiteralHIB = "GNHIB";

    /// <summary>
    /// Literal for code: HepatitisA
    /// </summary>
    public const string LiteralHepatitisA = "GNHPA";

    /// <summary>
    /// Literal for code: JapaneseEncephalitis_2
    /// </summary>
    public const string LiteralJapaneseEncephalitis_2 = "GNJEN";

    /// <summary>
    /// Literal for code: Measles_2
    /// </summary>
    public const string LiteralMeasles_2 = "GNMEA";

    /// <summary>
    /// Literal for code: MeningococcalC
    /// </summary>
    public const string LiteralMeningococcalC = "GNMEN";

    /// <summary>
    /// Literal for code: Mumps_2
    /// </summary>
    public const string LiteralMumps_2 = "GNMUM";

    /// <summary>
    /// Literal for code: Pneumococcal_2
    /// </summary>
    public const string LiteralPneumococcal_2 = "GNPNE";

    /// <summary>
    /// Literal for code: Polio
    /// </summary>
    public const string LiteralPolio = "GNPOL";

    /// <summary>
    /// Literal for code: Rotavirus
    /// </summary>
    public const string LiteralRotavirus = "GNROX";

    /// <summary>
    /// Literal for code: Rubella_2
    /// </summary>
    public const string LiteralRubella_2 = "GNRUB";

    /// <summary>
    /// Literal for code: Tetanus
    /// </summary>
    public const string LiteralTetanus = "GNTET";

    /// <summary>
    /// Literal for code: Varicella_2
    /// </summary>
    public const string LiteralVaricella_2 = "GNVAR";

    /// <summary>
    /// Literal for code: TwinrixJunior
    /// </summary>
    public const string LiteralTwinrixJunior = "HATWNJ";

    /// <summary>
    /// Literal for code: VaqtaPaedAdol
    /// </summary>
    public const string LiteralVaqtaPaedAdol = "HAVAQ";

    /// <summary>
    /// Literal for code: HavrixJunior
    /// </summary>
    public const string LiteralHavrixJunior = "HAVJ";

    /// <summary>
    /// Literal for code: HibTITER
    /// </summary>
    public const string LiteralHibTITER = "HBOC";

    /// <summary>
    /// Literal for code: HBV
    /// </summary>
    public const string LiteralHBV = "HBV";

    /// <summary>
    /// Literal for code: HBVAXII
    /// </summary>
    public const string LiteralHBVAXII = "HBVP";

    /// <summary>
    /// Literal for code: Hiberix
    /// </summary>
    public const string LiteralHiberix = "HBX";

    /// <summary>
    /// Literal for code: InfanrixHexa
    /// </summary>
    public const string LiteralInfanrixHexa = "IFHX";

    /// <summary>
    /// Literal for code: InfanrixIPV
    /// </summary>
    public const string LiteralInfanrixIPV = "IFIP";

    /// <summary>
    /// Literal for code: InfanrixPenta
    /// </summary>
    public const string LiteralInfanrixPenta = "IFPA";

    /// <summary>
    /// Literal for code: Infanrix
    /// </summary>
    public const string LiteralInfanrix = "IFX";

    /// <summary>
    /// Literal for code: InfanrixHepB
    /// </summary>
    public const string LiteralInfanrixHepB = "IFXB";

    /// <summary>
    /// Literal for code: Influvac
    /// </summary>
    public const string LiteralInfluvac = "INFLUV";

    /// <summary>
    /// Literal for code: IPOL
    /// </summary>
    public const string LiteralIPOL = "IPV";

    /// <summary>
    /// Literal for code: JEVAX
    /// </summary>
    public const string LiteralJEVAX = "JEVAX";

    /// <summary>
    /// Literal for code: Menjugate
    /// </summary>
    public const string LiteralMenjugate = "MENJUG";

    /// <summary>
    /// Literal for code: Meningitec
    /// </summary>
    public const string LiteralMeningitec = "MENTEC";

    /// <summary>
    /// Literal for code: Menomune
    /// </summary>
    public const string LiteralMenomune = "MENUME";

    /// <summary>
    /// Literal for code: MencevaxACWY
    /// </summary>
    public const string LiteralMencevaxACWY = "MENVAX";

    /// <summary>
    /// Literal for code: MMR_2
    /// </summary>
    public const string LiteralMMR_2 = "MMR";

    /// <summary>
    /// Literal for code: MMRII
    /// </summary>
    public const string LiteralMMRII = "MMRCSL";

    /// <summary>
    /// Literal for code: Priorix
    /// </summary>
    public const string LiteralPriorix = "MMRSKB";

    /// <summary>
    /// Literal for code: Menitorix
    /// </summary>
    public const string LiteralMenitorix = "MNTRX";

    /// <summary>
    /// Literal for code: NeisVacC
    /// </summary>
    public const string LiteralNeisVacC = "NEISVC";

    /// <summary>
    /// Literal for code: Polio_2
    /// </summary>
    public const string LiteralPolio_2 = "OPV";

    /// <summary>
    /// Literal for code: Pertussis_2
    /// </summary>
    public const string LiteralPertussis_2 = "P";

    /// <summary>
    /// Literal for code: Panvax
    /// </summary>
    public const string LiteralPanvax = "PANVAX";

    /// <summary>
    /// Literal for code: Pediacel
    /// </summary>
    public const string LiteralPediacel = "PDCL";

    /// <summary>
    /// Literal for code: Poliacel
    /// </summary>
    public const string LiteralPoliacel = "PLCL";

    /// <summary>
    /// Literal for code: Pneumovax
    /// </summary>
    public const string LiteralPneumovax = "PNEUMO";

    /// <summary>
    /// Literal for code: ProQuad
    /// </summary>
    public const string LiteralProQuad = "PROQAD";

    /// <summary>
    /// Literal for code: ProHIBit
    /// </summary>
    public const string LiteralProHIBit = "PRPD";

    /// <summary>
    /// Literal for code: PedvaxHIB
    /// </summary>
    public const string LiteralPedvaxHIB = "PRPOMP";

    /// <summary>
    /// Literal for code: ActHIB
    /// </summary>
    public const string LiteralActHIB = "PRPT";

    /// <summary>
    /// Literal for code: Prevenar7
    /// </summary>
    public const string LiteralPrevenar7 = "PRVNR";

    /// <summary>
    /// Literal for code: Prevenar13
    /// </summary>
    public const string LiteralPrevenar13 = "PRVTH";

    /// <summary>
    /// Literal for code: PriorixTetra
    /// </summary>
    public const string LiteralPriorixTetra = "PRXTEX";

    /// <summary>
    /// Literal for code: Quadracel
    /// </summary>
    public const string LiteralQuadracel = "QDCL";

    /// <summary>
    /// Literal for code: Rotarix
    /// </summary>
    public const string LiteralRotarix = "ROTRIX";

    /// <summary>
    /// Literal for code: Rotateq
    /// </summary>
    public const string LiteralRotateq = "ROTTEQ";

    /// <summary>
    /// Literal for code: Synflorix
    /// </summary>
    public const string LiteralSynflorix = "SYNFLX";

    /// <summary>
    /// Literal for code: Tripacel
    /// </summary>
    public const string LiteralTripacel = "TCL";

    /// <summary>
    /// Literal for code: Vaxigrip
    /// </summary>
    public const string LiteralVaxigrip = "VAXGRP";

    /// <summary>
    /// Literal for code: VaxigripJunior
    /// </summary>
    public const string LiteralVaxigripJunior = "VGRJNR";

    /// <summary>
    /// Literal for code: Varilrix
    /// </summary>
    public const string LiteralVarilrix = "VLRIX";

    /// <summary>
    /// Literal for code: Varivax
    /// </summary>
    public const string LiteralVarivax = "VRVAX";
  };
}
