// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The type of coordinates describing a 3D image region.
  /// </summary>
  public static class Imagingselection3dgraphictypeCodes
  {
    /// <summary>
    /// an ellipse defined by four (x,y,z) triplets, the first two triplets specifying the endpoints of the major axis and the second two triplets specifying the endpoints of the minor axis.
    /// </summary>
    public static readonly Coding ELLIPSE = new Coding
    {
      Code = "ELLIPSE",
      Display = "ELLIPSE",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };
    /// <summary>
    /// a three-dimensional geometric surface whose plane sections are either ellipses or circles and contains three intersecting orthogonal axes, "a", "b", and "c"; the ellipsoid is defined by six (x,y,z) triplets, the first and second triplets specifying the endpoints of axis "a", the third and fourth triplets specifying the endpoints of axis "b", and the fifth and sixth triplets specifying the endpoints of axis "c".
    /// </summary>
    public static readonly Coding ELLIPSOID = new Coding
    {
      Code = "ELLIPSOID",
      Display = "ELLIPSOID",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };
    /// <summary>
    /// multiple locations each denoted by an (x,y,z) triplet; the points need not be coplanar.
    /// </summary>
    public static readonly Coding MULTIPOINT = new Coding
    {
      Code = "MULTIPOINT",
      Display = "MULTIPOINT",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };
    /// <summary>
    /// A single location denoted by a single (x,y,z) triplet.
    /// </summary>
    public static readonly Coding POINT = new Coding
    {
      Code = "POINT",
      Display = "POINT",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };
    /// <summary>
    /// a series of connected line segments with ordered vertices denoted by (x,y,z) triplets, where the first and last vertices shall be the same forming a polygon; the points shall be coplanar.
    /// </summary>
    public static readonly Coding POLYGON = new Coding
    {
      Code = "POLYGON",
      Display = "POLYGON",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };
    /// <summary>
    /// a series of connected line segments with ordered vertices denoted by (x,y,z) triplets; the points need not be coplanar.
    /// </summary>
    public static readonly Coding POLYLINE = new Coding
    {
      Code = "POLYLINE",
      Display = "POLYLINE",
      System = "http://hl7.org/fhir/imagingselection-3dgraphictype"
    };

    /// <summary>
    /// Literal for code: ELLIPSE
    /// </summary>
    public const string LiteralELLIPSE = "ELLIPSE";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypeELLIPSE
    /// </summary>
    public const string LiteralImagingselection3dgraphictypeELLIPSE = "http://hl7.org/fhir/imagingselection-3dgraphictype#ELLIPSE";

    /// <summary>
    /// Literal for code: ELLIPSOID
    /// </summary>
    public const string LiteralELLIPSOID = "ELLIPSOID";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypeELLIPSOID
    /// </summary>
    public const string LiteralImagingselection3dgraphictypeELLIPSOID = "http://hl7.org/fhir/imagingselection-3dgraphictype#ELLIPSOID";

    /// <summary>
    /// Literal for code: MULTIPOINT
    /// </summary>
    public const string LiteralMULTIPOINT = "MULTIPOINT";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypeMULTIPOINT
    /// </summary>
    public const string LiteralImagingselection3dgraphictypeMULTIPOINT = "http://hl7.org/fhir/imagingselection-3dgraphictype#MULTIPOINT";

    /// <summary>
    /// Literal for code: POINT
    /// </summary>
    public const string LiteralPOINT = "POINT";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypePOINT
    /// </summary>
    public const string LiteralImagingselection3dgraphictypePOINT = "http://hl7.org/fhir/imagingselection-3dgraphictype#POINT";

    /// <summary>
    /// Literal for code: POLYGON
    /// </summary>
    public const string LiteralPOLYGON = "POLYGON";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypePOLYGON
    /// </summary>
    public const string LiteralImagingselection3dgraphictypePOLYGON = "http://hl7.org/fhir/imagingselection-3dgraphictype#POLYGON";

    /// <summary>
    /// Literal for code: POLYLINE
    /// </summary>
    public const string LiteralPOLYLINE = "POLYLINE";

    /// <summary>
    /// Literal for code: Imagingselection3dgraphictypePOLYLINE
    /// </summary>
    public const string LiteralImagingselection3dgraphictypePOLYLINE = "http://hl7.org/fhir/imagingselection-3dgraphictype#POLYLINE";

    /// <summary>
    /// Dictionary for looking up Imagingselection3dgraphictype Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "ELLIPSE", ELLIPSE }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#ELLIPSE", ELLIPSE }, 
      { "ELLIPSOID", ELLIPSOID }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#ELLIPSOID", ELLIPSOID }, 
      { "MULTIPOINT", MULTIPOINT }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#MULTIPOINT", MULTIPOINT }, 
      { "POINT", POINT }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#POINT", POINT }, 
      { "POLYGON", POLYGON }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#POLYGON", POLYGON }, 
      { "POLYLINE", POLYLINE }, 
      { "http://hl7.org/fhir/imagingselection-3dgraphictype#POLYLINE", POLYLINE }, 
    };
  };
}
