// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The type of relationship to the cited artifact.
  /// </summary>
  public static class RelatedArtifactTypeExpandedCodes
  {
    /// <summary>
    /// This artifact is amended with or changed by the target artifact. There is information in this artifact that should be functionally replaced with information in the target artifact.
    /// </summary>
    public static readonly Coding AmendedWith = new Coding
    {
      Code = "amended-with",
      Display = "Amended With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact amends or changes the target artifact. This artifact adds additional information that is functionally expected to replace information in the target artifact. This artifact replaces a part but not all of the target artifact.
    /// </summary>
    public static readonly Coding Amends = new Coding
    {
      Code = "amends",
      Display = "Amends",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact has additional information in the target artifact.
    /// </summary>
    public static readonly Coding AppendedWith = new Coding
    {
      Code = "appended-with",
      Display = "Appended With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact adds additional information to the target artifact. The additional information does not replace or change information in the target artifact.
    /// </summary>
    public static readonly Coding Appends = new Coding
    {
      Code = "appends",
      Display = "Appends",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The related artifact is the citation for this artifact.
    /// </summary>
    public static readonly Coding CitationFor = new Coding
    {
      Code = "cite-as",
      Display = "Citation for",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is cited by the target artifact.
    /// </summary>
    public static readonly Coding CitedBy = new Coding
    {
      Code = "cited-by",
      Display = "Cited By",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact cites the target artifact. This may be a bibliographic citation for papers, references, or other relevant material for the knowledge resource. This is intended to allow for citation of related material, but that was not necessarily specifically prepared in connection with this knowledge resource.
    /// </summary>
    public static readonly Coding Cites = new Coding
    {
      Code = "cites",
      Display = "Cites",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact has comments about it in the target artifact.  The type of comments may be expressed in the targetClassifier element such as reply, review, editorial, feedback, solicited, unsolicited, structured, unstructured.
    /// </summary>
    public static readonly Coding HasCommentIn = new Coding
    {
      Code = "comment-in",
      Display = "Has Comment In",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact contains comments about the target artifact. 
    /// </summary>
    public static readonly Coding IsCommentOn = new Coding
    {
      Code = "comments-on",
      Display = "Is Comment On",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is composed of the target artifact. This artifact is constructed with the target artifact as a component. The target artifact is a part of this artifact. (A dataset is composed of data.)
    /// </summary>
    public static readonly Coding ComposedOf = new Coding
    {
      Code = "composed-of",
      Display = "Composed Of",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is contained in the target artifact. The target artifact is a data structure whose instances are collections of other objects.
    /// </summary>
    public static readonly Coding ContainedIn = new Coding
    {
      Code = "contained-in",
      Display = "Contained In",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is a container in which the target artifact is contained. A container is a data structure whose instances are collections of other objects. (A database contains the dataset.)
    /// </summary>
    public static readonly Coding Contains = new Coding
    {
      Code = "contains",
      Display = "Contains",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact has corrections to it in the target artifact. The target artifact identifies errors and replacement content for this artifact.
    /// </summary>
    public static readonly Coding CorrectionIn = new Coding
    {
      Code = "correction-in",
      Display = "Correction In",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact identifies errors and replacement content for the target artifact.
    /// </summary>
    public static readonly Coding Corrects = new Coding
    {
      Code = "corrects",
      Display = "Corrects",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact was created with the target artifact. The target artifact is a tool or support material used in the creation of the artifact, and not content that the artifact was derived from.
    /// </summary>
    public static readonly Coding CreatedWith = new Coding
    {
      Code = "created-with",
      Display = "Created With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact depends on the target artifact. There is a requirement to use the target artifact in the implementation or interpretation of this artifact.
    /// </summary>
    public static readonly Coding DependsOn = new Coding
    {
      Code = "depends-on",
      Display = "Depends On",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is derived from the target artifact. This is intended to capture the relationship in which a particular knowledge resource is based on the content of another artifact, but is modified to capture either a different set of overall requirements, or a more specific set of requirements such as those involved in a particular institution or clinical setting. The artifact may be derived from one or more target artifacts.
    /// </summary>
    public static readonly Coding DerivedFrom = new Coding
    {
      Code = "derived-from",
      Display = "Derived From",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// Additional documentation for the knowledge resource. This would include additional instructions on usage as well as additional information on clinical context or appropriateness
    /// </summary>
    public static readonly Coding Documentation = new Coding
    {
      Code = "documentation",
      Display = "Documentation",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact provides additional documentation for the target artifact. This could include additional instructions on usage as well as additional information on clinical context or appropriateness.
    /// </summary>
    public static readonly Coding Documents = new Coding
    {
      Code = "documents",
      Display = "Documents",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The target artifact is a summary of the justification for the knowledge resource including supporting evidence, relevant guidelines, or other clinically important information. This information is intended to provide a way to make the justification for the knowledge resource available to the consumer of interventions or results produced by the knowledge resource.
    /// </summary>
    public static readonly Coding Justification = new Coding
    {
      Code = "justification",
      Display = "Justification",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is a part of the target artifact. The target artifact is composed of this artifact (and possibly other artifacts).
    /// </summary>
    public static readonly Coding PartOf = new Coding
    {
      Code = "part-of",
      Display = "Part Of",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The previous version of the knowledge artifact, used to establish an ordering of versions of an artifact, independent of the status of each version.
    /// </summary>
    public static readonly Coding Predecessor = new Coding
    {
      Code = "predecessor",
      Display = "Predecessor",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is replaced with or superseded by the target artifact. This artifact may be considered deprecated.
    /// </summary>
    public static readonly Coding ReplacedWith = new Coding
    {
      Code = "replaced-with",
      Display = "Replaced With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact replaces or supersedes the target artifact. The target artifact may be considered deprecated.
    /// </summary>
    public static readonly Coding Replaces = new Coding
    {
      Code = "replaces",
      Display = "Replaces",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// A copy of the artifact in a publication with a different artifact identifier.
    /// </summary>
    public static readonly Coding Reprint = new Coding
    {
      Code = "reprint",
      Display = "Reprint",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The original version of record for which the current artifact is a copy.
    /// </summary>
    public static readonly Coding ReprintOf = new Coding
    {
      Code = "reprint-of",
      Display = "Reprint Of",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is retracted by the target artifact. The content that was published in this artifact should be considered removed from publication and should no longer be considered part of the public record.
    /// </summary>
    public static readonly Coding RetractedBy = new Coding
    {
      Code = "retracted-by",
      Display = "Retracted By",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact retracts the target artifact. The content that was published in the target artifact should be considered removed from publication and should no longer be considered part of the public record.
    /// </summary>
    public static readonly Coding Retracts = new Coding
    {
      Code = "retracts",
      Display = "Retracts",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact is a signature of the target artifact.
    /// </summary>
    public static readonly Coding Signs = new Coding
    {
      Code = "signs",
      Display = "Signs",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact has characteristics in common with the target artifact. This relationship may be used in systems to “deduplicate” knowledge artifacts from different sources, or in systems to show “similar items”.
    /// </summary>
    public static readonly Coding SimilarTo = new Coding
    {
      Code = "similar-to",
      Display = "Similar To",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The target artifact is a precise description of a concept in this artifact. This may be used when the RelatedArtifact datatype is used in elements contained in this artifact.
    /// </summary>
    public static readonly Coding SpecificationOf = new Coding
    {
      Code = "specification-of",
      Display = "Specification of",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The subsequent version of the knowledge artfact, used to establish an ordering of versions of an artifact, independent of the status of each version.
    /// </summary>
    public static readonly Coding Successor = new Coding
    {
      Code = "successor",
      Display = "Successor",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// The target artifact contains additional information related to the knowledge artifact but is not documentation as the additional information does not describe, explain, or instruct regarding the knowledge artifact content or application. This could include an associated dataset.
    /// </summary>
    public static readonly Coding SupportedWith = new Coding
    {
      Code = "supported-with",
      Display = "Supported With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact provides additional support for the target artifact. The type of support  is not documentation as it does not describe, explain, or instruct regarding the target artifact.
    /// </summary>
    public static readonly Coding Supports = new Coding
    {
      Code = "supports",
      Display = "Supports",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact was transformed into the target artifact (e.g., by format or language conversion).
    /// </summary>
    public static readonly Coding TransformedInto = new Coding
    {
      Code = "transformed-into",
      Display = "Transformed Into",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact was generated by transforming a related artifact (e.g., format or language conversion), noted separately with the “transforms” relationship type. This transformation used the target artifact to inform the transformation. The target artifact may be a conversion script or translation guide.
    /// </summary>
    public static readonly Coding TransformedWith = new Coding
    {
      Code = "transformed-with",
      Display = "Transformed With",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };
    /// <summary>
    /// This artifact was generated by transforming the target artifact (e.g., format or language conversion). This is intended to capture the relationship in which a particular knowledge resource is based on the content of another artifact, but changes are only apparent in form and there is only one target artifact with the “transforms” relationship type.
    /// </summary>
    public static readonly Coding Transforms = new Coding
    {
      Code = "transforms",
      Display = "Transforms",
      System = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded"
    };

    /// <summary>
    /// Literal for code: AmendedWith
    /// </summary>
    public const string LiteralAmendedWith = "amended-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedAmendedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedAmendedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#amended-with";

    /// <summary>
    /// Literal for code: Amends
    /// </summary>
    public const string LiteralAmends = "amends";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedAmends
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedAmends = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#amends";

    /// <summary>
    /// Literal for code: AppendedWith
    /// </summary>
    public const string LiteralAppendedWith = "appended-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedAppendedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedAppendedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#appended-with";

    /// <summary>
    /// Literal for code: Appends
    /// </summary>
    public const string LiteralAppends = "appends";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedAppends
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedAppends = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#appends";

    /// <summary>
    /// Literal for code: CitationFor
    /// </summary>
    public const string LiteralCitationFor = "cite-as";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCitationFor
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCitationFor = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cite-as";

    /// <summary>
    /// Literal for code: CitedBy
    /// </summary>
    public const string LiteralCitedBy = "cited-by";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCitedBy
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCitedBy = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cited-by";

    /// <summary>
    /// Literal for code: Cites
    /// </summary>
    public const string LiteralCites = "cites";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCites
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCites = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cites";

    /// <summary>
    /// Literal for code: HasCommentIn
    /// </summary>
    public const string LiteralHasCommentIn = "comment-in";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedHasCommentIn
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedHasCommentIn = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#comment-in";

    /// <summary>
    /// Literal for code: IsCommentOn
    /// </summary>
    public const string LiteralIsCommentOn = "comments-on";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedIsCommentOn
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedIsCommentOn = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#comments-on";

    /// <summary>
    /// Literal for code: ComposedOf
    /// </summary>
    public const string LiteralComposedOf = "composed-of";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedComposedOf
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedComposedOf = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#composed-of";

    /// <summary>
    /// Literal for code: ContainedIn
    /// </summary>
    public const string LiteralContainedIn = "contained-in";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedContainedIn
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedContainedIn = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#contained-in";

    /// <summary>
    /// Literal for code: Contains
    /// </summary>
    public const string LiteralContains = "contains";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedContains
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedContains = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#contains";

    /// <summary>
    /// Literal for code: CorrectionIn
    /// </summary>
    public const string LiteralCorrectionIn = "correction-in";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCorrectionIn
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCorrectionIn = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#correction-in";

    /// <summary>
    /// Literal for code: Corrects
    /// </summary>
    public const string LiteralCorrects = "corrects";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCorrects
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCorrects = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#corrects";

    /// <summary>
    /// Literal for code: CreatedWith
    /// </summary>
    public const string LiteralCreatedWith = "created-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedCreatedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedCreatedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#created-with";

    /// <summary>
    /// Literal for code: DependsOn
    /// </summary>
    public const string LiteralDependsOn = "depends-on";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedDependsOn
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedDependsOn = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#depends-on";

    /// <summary>
    /// Literal for code: DerivedFrom
    /// </summary>
    public const string LiteralDerivedFrom = "derived-from";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedDerivedFrom
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedDerivedFrom = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#derived-from";

    /// <summary>
    /// Literal for code: Documentation
    /// </summary>
    public const string LiteralDocumentation = "documentation";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedDocumentation
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedDocumentation = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#documentation";

    /// <summary>
    /// Literal for code: Documents
    /// </summary>
    public const string LiteralDocuments = "documents";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedDocuments
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedDocuments = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#documents";

    /// <summary>
    /// Literal for code: Justification
    /// </summary>
    public const string LiteralJustification = "justification";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedJustification
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedJustification = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#justification";

    /// <summary>
    /// Literal for code: PartOf
    /// </summary>
    public const string LiteralPartOf = "part-of";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedPartOf
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedPartOf = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#part-of";

    /// <summary>
    /// Literal for code: Predecessor
    /// </summary>
    public const string LiteralPredecessor = "predecessor";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedPredecessor
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedPredecessor = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#predecessor";

    /// <summary>
    /// Literal for code: ReplacedWith
    /// </summary>
    public const string LiteralReplacedWith = "replaced-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedReplacedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedReplacedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#replaced-with";

    /// <summary>
    /// Literal for code: Replaces
    /// </summary>
    public const string LiteralReplaces = "replaces";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedReplaces
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedReplaces = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#replaces";

    /// <summary>
    /// Literal for code: Reprint
    /// </summary>
    public const string LiteralReprint = "reprint";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedReprint
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedReprint = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#reprint";

    /// <summary>
    /// Literal for code: ReprintOf
    /// </summary>
    public const string LiteralReprintOf = "reprint-of";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedReprintOf
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedReprintOf = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#reprint-of";

    /// <summary>
    /// Literal for code: RetractedBy
    /// </summary>
    public const string LiteralRetractedBy = "retracted-by";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedRetractedBy
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedRetractedBy = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#retracted-by";

    /// <summary>
    /// Literal for code: Retracts
    /// </summary>
    public const string LiteralRetracts = "retracts";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedRetracts
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedRetracts = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#retracts";

    /// <summary>
    /// Literal for code: Signs
    /// </summary>
    public const string LiteralSigns = "signs";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSigns
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSigns = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#signs";

    /// <summary>
    /// Literal for code: SimilarTo
    /// </summary>
    public const string LiteralSimilarTo = "similar-to";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSimilarTo
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSimilarTo = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#similar-to";

    /// <summary>
    /// Literal for code: SpecificationOf
    /// </summary>
    public const string LiteralSpecificationOf = "specification-of";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSpecificationOf
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSpecificationOf = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#specification-of";

    /// <summary>
    /// Literal for code: Successor
    /// </summary>
    public const string LiteralSuccessor = "successor";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSuccessor
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSuccessor = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#successor";

    /// <summary>
    /// Literal for code: SupportedWith
    /// </summary>
    public const string LiteralSupportedWith = "supported-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSupportedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSupportedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#supported-with";

    /// <summary>
    /// Literal for code: Supports
    /// </summary>
    public const string LiteralSupports = "supports";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedSupports
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedSupports = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#supports";

    /// <summary>
    /// Literal for code: TransformedInto
    /// </summary>
    public const string LiteralTransformedInto = "transformed-into";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedTransformedInto
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedTransformedInto = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transformed-into";

    /// <summary>
    /// Literal for code: TransformedWith
    /// </summary>
    public const string LiteralTransformedWith = "transformed-with";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedTransformedWith
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedTransformedWith = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transformed-with";

    /// <summary>
    /// Literal for code: Transforms
    /// </summary>
    public const string LiteralTransforms = "transforms";

    /// <summary>
    /// Literal for code: RelatedArtifactTypeExpandedTransforms
    /// </summary>
    public const string LiteralRelatedArtifactTypeExpandedTransforms = "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transforms";

    /// <summary>
    /// Dictionary for looking up RelatedArtifactTypeExpanded Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "amended-with", AmendedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#amended-with", AmendedWith }, 
      { "amends", Amends }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#amends", Amends }, 
      { "appended-with", AppendedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#appended-with", AppendedWith }, 
      { "appends", Appends }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#appends", Appends }, 
      { "cite-as", CitationFor }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cite-as", CitationFor }, 
      { "cited-by", CitedBy }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cited-by", CitedBy }, 
      { "cites", Cites }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#cites", Cites }, 
      { "comment-in", HasCommentIn }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#comment-in", HasCommentIn }, 
      { "comments-on", IsCommentOn }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#comments-on", IsCommentOn }, 
      { "composed-of", ComposedOf }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#composed-of", ComposedOf }, 
      { "contained-in", ContainedIn }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#contained-in", ContainedIn }, 
      { "contains", Contains }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#contains", Contains }, 
      { "correction-in", CorrectionIn }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#correction-in", CorrectionIn }, 
      { "corrects", Corrects }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#corrects", Corrects }, 
      { "created-with", CreatedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#created-with", CreatedWith }, 
      { "depends-on", DependsOn }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#depends-on", DependsOn }, 
      { "derived-from", DerivedFrom }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#derived-from", DerivedFrom }, 
      { "documentation", Documentation }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#documentation", Documentation }, 
      { "documents", Documents }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#documents", Documents }, 
      { "justification", Justification }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#justification", Justification }, 
      { "part-of", PartOf }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#part-of", PartOf }, 
      { "predecessor", Predecessor }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#predecessor", Predecessor }, 
      { "replaced-with", ReplacedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#replaced-with", ReplacedWith }, 
      { "replaces", Replaces }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#replaces", Replaces }, 
      { "reprint", Reprint }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#reprint", Reprint }, 
      { "reprint-of", ReprintOf }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#reprint-of", ReprintOf }, 
      { "retracted-by", RetractedBy }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#retracted-by", RetractedBy }, 
      { "retracts", Retracts }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#retracts", Retracts }, 
      { "signs", Signs }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#signs", Signs }, 
      { "similar-to", SimilarTo }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#similar-to", SimilarTo }, 
      { "specification-of", SpecificationOf }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#specification-of", SpecificationOf }, 
      { "successor", Successor }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#successor", Successor }, 
      { "supported-with", SupportedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#supported-with", SupportedWith }, 
      { "supports", Supports }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#supports", Supports }, 
      { "transformed-into", TransformedInto }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transformed-into", TransformedInto }, 
      { "transformed-with", TransformedWith }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transformed-with", TransformedWith }, 
      { "transforms", Transforms }, 
      { "http://terminology.hl7.org/CodeSystem/related-artifact-type-expanded#transforms", Transforms }, 
    };
  };
}
