// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// This is a ResearchStudy's party organization type.
  /// </summary>
  public static class ResearchStudyPartyOrgTypeCodes
  {
    /// <summary>
    /// FDA
    /// </summary>
    public static readonly Coding FDA = new Coding
    {
      Code = "fda",
      Display = "FDA",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// NIH
    /// </summary>
    public static readonly Coding NIH = new Coding
    {
      Code = "nih",
      Display = "NIH",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };

    /// <summary>
    /// Literal for code: FDA
    /// </summary>
    public const string LiteralFDA = "fda";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersFDA
    /// </summary>
    public const string LiteralResearchStudyClassifiersFDA = "http://hl7.org/fhir/research-study-classifiers#fda";

    /// <summary>
    /// Literal for code: NIH
    /// </summary>
    public const string LiteralNIH = "nih";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersNIH
    /// </summary>
    public const string LiteralResearchStudyClassifiersNIH = "http://hl7.org/fhir/research-study-classifiers#nih";

    /// <summary>
    /// Dictionary for looking up ResearchStudyPartyOrgType Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "fda", FDA }, 
      { "http://hl7.org/fhir/research-study-classifiers#fda", FDA }, 
      { "nih", NIH }, 
      { "http://hl7.org/fhir/research-study-classifiers#nih", NIH }, 
    };
  };
}
