// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Codes that convey the type of label that is provided.
  /// </summary>
  public static class ResearchStudyClassifiersCodes
  {
    /// <summary>
    /// One or more interventions for examining the basic mechanism of action (for example, physiology or biomechanics of an intervention).
    /// </summary>
    public static readonly Coding BasicScience = new Coding
    {
      Code = "basic-science",
      Display = "Basic Science",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Device
    /// </summary>
    public static readonly Coding Device = new Coding
    {
      Code = "device",
      Display = "Device",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// An intervention of a device product is being evaluated to determine the feasibility of the product or to test a prototype device and not health outcomes. Such studies are conducted to confirm the design and operating specifications of a device before beginning a full clinical trial.
    /// </summary>
    public static readonly Coding DeviceFeasibility = new Coding
    {
      Code = "device-feasibility",
      Display = "Device Feasibility",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions are being evaluated for identifying a disease or health condition.
    /// </summary>
    public static readonly Coding Diagnostic = new Coding
    {
      Code = "diagnostic",
      Display = "Diagnostic",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Designation for optional exploratory trials conducted in accordance with the United States Food and Drug Administration's (FDA) 2006 Guidance on Exploratory Investigational New Drug (IND) Studies. Formerly called Phase 0.
    /// </summary>
    public static readonly Coding EarlyPhase1 = new Coding
    {
      Code = "early-phase-1",
      Display = "Early Phase 1",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Factor
    /// </summary>
    public static readonly Coding Factor = new Coding
    {
      Code = "factor",
      Display = "Factor",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions for evaluating the delivery, processes, management, organization, or financing of healthcare.
    /// </summary>
    public static readonly Coding HealthServicesResearch = new Coding
    {
      Code = "health-services-research",
      Display = "Health Services Research",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Intervention
    /// </summary>
    public static readonly Coding Intervention = new Coding
    {
      Code = "intervention",
      Display = "Intervention",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Medication
    /// </summary>
    public static readonly Coding Medication = new Coding
    {
      Code = "medication",
      Display = "Medication",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Trials without phases (for example, studies of devices or behavioral interventions).
    /// </summary>
    public static readonly Coding NA = new Coding
    {
      Code = "n-a",
      Display = "N/A",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Includes initial studies to determine the metabolism and pharmacologic actions of drugs in humans, the side effects associated with increasing doses, and to gain early evidence of effectiveness; may include healthy participants and/or patients.
    /// </summary>
    public static readonly Coding Phase1 = new Coding
    {
      Code = "phase-1",
      Display = "Phase 1",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Trials that are a combination of phases 1 and 2.
    /// </summary>
    public static readonly Coding Phase1Phase2 = new Coding
    {
      Code = "phase-1-phase-2",
      Display = "Phase 1/Phase 2",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Includes controlled clinical studies conducted to evaluate the effectiveness of the drug for a particular indication or indications in participants with the disease or condition under study and to determine the common short-term side effects and risks.
    /// </summary>
    public static readonly Coding Phase2 = new Coding
    {
      Code = "phase-2",
      Display = "Phase 2",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Trials that are a combination of phases 2 and 3.
    /// </summary>
    public static readonly Coding Phase2Phase3 = new Coding
    {
      Code = "phase-2-phase-3",
      Display = "Phase 2/Phase 3",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Includes trials conducted after preliminary evidence suggesting effectiveness of the drug has been obtained, and are intended to gather additional information to evaluate the overall benefit-risk relationship of the drug.
    /// </summary>
    public static readonly Coding Phase3 = new Coding
    {
      Code = "phase-3",
      Display = "Phase 3",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Studies of FDA-approved drugs to delineate additional information including the drug's risks, benefits, and optimal use.
    /// </summary>
    public static readonly Coding Phase4 = new Coding
    {
      Code = "phase-4",
      Display = "Phase 4",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions are being assessed for preventing the development of a specific disease or health condition.
    /// </summary>
    public static readonly Coding Prevention = new Coding
    {
      Code = "prevention",
      Display = "Prevention",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Research Study Focus Type
    /// </summary>
    public static readonly Coding ResearchStudyFocusType = new Coding
    {
      Code = "research-study-focus-type",
      Display = "Research Study Focus Type",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Research Study Phase
    /// </summary>
    public static readonly Coding ResearchStudyPhase = new Coding
    {
      Code = "research-study-phase",
      Display = "Research Study Phase",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Research Study Primary Purpose Type
    /// </summary>
    public static readonly Coding ResearchStudyPrimaryPurposeType = new Coding
    {
      Code = "research-study-prim-purp-type",
      Display = "Research Study Primary Purpose Type",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions are assessed or examined for identifying a condition, or risk factors for a condition, in people who are not yet known to have the condition or risk factor.
    /// </summary>
    public static readonly Coding Screening = new Coding
    {
      Code = "screening",
      Display = "Screening",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions are evaluated for maximizing comfort, minimizing side effects, or mitigating against a decline in the participant's health or function.
    /// </summary>
    public static readonly Coding SupportiveCare = new Coding
    {
      Code = "supportive-care",
      Display = "Supportive Care",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// One or more interventions are being evaluated for treating a disease, syndrome, or condition.
    /// </summary>
    public static readonly Coding Treatment = new Coding
    {
      Code = "treatment",
      Display = "Treatment",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };

    /// <summary>
    /// Literal for code: BasicScience
    /// </summary>
    public const string LiteralBasicScience = "basic-science";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersBasicScience
    /// </summary>
    public const string LiteralResearchStudyClassifiersBasicScience = "http://hl7.org/fhir/research-study-classifiers#basic-science";

    /// <summary>
    /// Literal for code: Device
    /// </summary>
    public const string LiteralDevice = "device";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersDevice
    /// </summary>
    public const string LiteralResearchStudyClassifiersDevice = "http://hl7.org/fhir/research-study-classifiers#device";

    /// <summary>
    /// Literal for code: DeviceFeasibility
    /// </summary>
    public const string LiteralDeviceFeasibility = "device-feasibility";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersDeviceFeasibility
    /// </summary>
    public const string LiteralResearchStudyClassifiersDeviceFeasibility = "http://hl7.org/fhir/research-study-classifiers#device-feasibility";

    /// <summary>
    /// Literal for code: Diagnostic
    /// </summary>
    public const string LiteralDiagnostic = "diagnostic";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersDiagnostic
    /// </summary>
    public const string LiteralResearchStudyClassifiersDiagnostic = "http://hl7.org/fhir/research-study-classifiers#diagnostic";

    /// <summary>
    /// Literal for code: EarlyPhase1
    /// </summary>
    public const string LiteralEarlyPhase1 = "early-phase-1";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersEarlyPhase1
    /// </summary>
    public const string LiteralResearchStudyClassifiersEarlyPhase1 = "http://hl7.org/fhir/research-study-classifiers#early-phase-1";

    /// <summary>
    /// Literal for code: Factor
    /// </summary>
    public const string LiteralFactor = "factor";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersFactor
    /// </summary>
    public const string LiteralResearchStudyClassifiersFactor = "http://hl7.org/fhir/research-study-classifiers#factor";

    /// <summary>
    /// Literal for code: HealthServicesResearch
    /// </summary>
    public const string LiteralHealthServicesResearch = "health-services-research";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersHealthServicesResearch
    /// </summary>
    public const string LiteralResearchStudyClassifiersHealthServicesResearch = "http://hl7.org/fhir/research-study-classifiers#health-services-research";

    /// <summary>
    /// Literal for code: Intervention
    /// </summary>
    public const string LiteralIntervention = "intervention";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersIntervention
    /// </summary>
    public const string LiteralResearchStudyClassifiersIntervention = "http://hl7.org/fhir/research-study-classifiers#intervention";

    /// <summary>
    /// Literal for code: Medication
    /// </summary>
    public const string LiteralMedication = "medication";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersMedication
    /// </summary>
    public const string LiteralResearchStudyClassifiersMedication = "http://hl7.org/fhir/research-study-classifiers#medication";

    /// <summary>
    /// Literal for code: NA
    /// </summary>
    public const string LiteralNA = "n-a";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersNA
    /// </summary>
    public const string LiteralResearchStudyClassifiersNA = "http://hl7.org/fhir/research-study-classifiers#n-a";

    /// <summary>
    /// Literal for code: Phase1
    /// </summary>
    public const string LiteralPhase1 = "phase-1";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase1
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase1 = "http://hl7.org/fhir/research-study-classifiers#phase-1";

    /// <summary>
    /// Literal for code: Phase1Phase2
    /// </summary>
    public const string LiteralPhase1Phase2 = "phase-1-phase-2";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase1Phase2
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase1Phase2 = "http://hl7.org/fhir/research-study-classifiers#phase-1-phase-2";

    /// <summary>
    /// Literal for code: Phase2
    /// </summary>
    public const string LiteralPhase2 = "phase-2";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase2
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase2 = "http://hl7.org/fhir/research-study-classifiers#phase-2";

    /// <summary>
    /// Literal for code: Phase2Phase3
    /// </summary>
    public const string LiteralPhase2Phase3 = "phase-2-phase-3";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase2Phase3
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase2Phase3 = "http://hl7.org/fhir/research-study-classifiers#phase-2-phase-3";

    /// <summary>
    /// Literal for code: Phase3
    /// </summary>
    public const string LiteralPhase3 = "phase-3";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase3
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase3 = "http://hl7.org/fhir/research-study-classifiers#phase-3";

    /// <summary>
    /// Literal for code: Phase4
    /// </summary>
    public const string LiteralPhase4 = "phase-4";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase4
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase4 = "http://hl7.org/fhir/research-study-classifiers#phase-4";

    /// <summary>
    /// Literal for code: Prevention
    /// </summary>
    public const string LiteralPrevention = "prevention";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPrevention
    /// </summary>
    public const string LiteralResearchStudyClassifiersPrevention = "http://hl7.org/fhir/research-study-classifiers#prevention";

    /// <summary>
    /// Literal for code: ResearchStudyFocusType
    /// </summary>
    public const string LiteralResearchStudyFocusType = "research-study-focus-type";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersResearchStudyFocusType
    /// </summary>
    public const string LiteralResearchStudyClassifiersResearchStudyFocusType = "http://hl7.org/fhir/research-study-classifiers#research-study-focus-type";

    /// <summary>
    /// Literal for code: ResearchStudyPhase
    /// </summary>
    public const string LiteralResearchStudyPhase = "research-study-phase";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersResearchStudyPhase
    /// </summary>
    public const string LiteralResearchStudyClassifiersResearchStudyPhase = "http://hl7.org/fhir/research-study-classifiers#research-study-phase";

    /// <summary>
    /// Literal for code: ResearchStudyPrimaryPurposeType
    /// </summary>
    public const string LiteralResearchStudyPrimaryPurposeType = "research-study-prim-purp-type";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersResearchStudyPrimaryPurposeType
    /// </summary>
    public const string LiteralResearchStudyClassifiersResearchStudyPrimaryPurposeType = "http://hl7.org/fhir/research-study-classifiers#research-study-prim-purp-type";

    /// <summary>
    /// Literal for code: Screening
    /// </summary>
    public const string LiteralScreening = "screening";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersScreening
    /// </summary>
    public const string LiteralResearchStudyClassifiersScreening = "http://hl7.org/fhir/research-study-classifiers#screening";

    /// <summary>
    /// Literal for code: SupportiveCare
    /// </summary>
    public const string LiteralSupportiveCare = "supportive-care";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersSupportiveCare
    /// </summary>
    public const string LiteralResearchStudyClassifiersSupportiveCare = "http://hl7.org/fhir/research-study-classifiers#supportive-care";

    /// <summary>
    /// Literal for code: Treatment
    /// </summary>
    public const string LiteralTreatment = "treatment";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersTreatment
    /// </summary>
    public const string LiteralResearchStudyClassifiersTreatment = "http://hl7.org/fhir/research-study-classifiers#treatment";

    /// <summary>
    /// Dictionary for looking up ResearchStudyClassifiers Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "basic-science", BasicScience }, 
      { "http://hl7.org/fhir/research-study-classifiers#basic-science", BasicScience }, 
      { "device", Device }, 
      { "http://hl7.org/fhir/research-study-classifiers#device", Device }, 
      { "device-feasibility", DeviceFeasibility }, 
      { "http://hl7.org/fhir/research-study-classifiers#device-feasibility", DeviceFeasibility }, 
      { "diagnostic", Diagnostic }, 
      { "http://hl7.org/fhir/research-study-classifiers#diagnostic", Diagnostic }, 
      { "early-phase-1", EarlyPhase1 }, 
      { "http://hl7.org/fhir/research-study-classifiers#early-phase-1", EarlyPhase1 }, 
      { "factor", Factor }, 
      { "http://hl7.org/fhir/research-study-classifiers#factor", Factor }, 
      { "health-services-research", HealthServicesResearch }, 
      { "http://hl7.org/fhir/research-study-classifiers#health-services-research", HealthServicesResearch }, 
      { "intervention", Intervention }, 
      { "http://hl7.org/fhir/research-study-classifiers#intervention", Intervention }, 
      { "medication", Medication }, 
      { "http://hl7.org/fhir/research-study-classifiers#medication", Medication }, 
      { "n-a", NA }, 
      { "http://hl7.org/fhir/research-study-classifiers#n-a", NA }, 
      { "phase-1", Phase1 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-1", Phase1 }, 
      { "phase-1-phase-2", Phase1Phase2 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-1-phase-2", Phase1Phase2 }, 
      { "phase-2", Phase2 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-2", Phase2 }, 
      { "phase-2-phase-3", Phase2Phase3 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-2-phase-3", Phase2Phase3 }, 
      { "phase-3", Phase3 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-3", Phase3 }, 
      { "phase-4", Phase4 }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase-4", Phase4 }, 
      { "prevention", Prevention }, 
      { "http://hl7.org/fhir/research-study-classifiers#prevention", Prevention }, 
      { "research-study-focus-type", ResearchStudyFocusType }, 
      { "http://hl7.org/fhir/research-study-classifiers#research-study-focus-type", ResearchStudyFocusType }, 
      { "research-study-phase", ResearchStudyPhase }, 
      { "http://hl7.org/fhir/research-study-classifiers#research-study-phase", ResearchStudyPhase }, 
      { "research-study-prim-purp-type", ResearchStudyPrimaryPurposeType }, 
      { "http://hl7.org/fhir/research-study-classifiers#research-study-prim-purp-type", ResearchStudyPrimaryPurposeType }, 
      { "screening", Screening }, 
      { "http://hl7.org/fhir/research-study-classifiers#screening", Screening }, 
      { "supportive-care", SupportiveCare }, 
      { "http://hl7.org/fhir/research-study-classifiers#supportive-care", SupportiveCare }, 
      { "treatment", Treatment }, 
      { "http://hl7.org/fhir/research-study-classifiers#treatment", Treatment }, 
    };
  };
}
