// <auto-generated />
// Built from: hl7.fhir.r5.core version: 4.6.0
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Codes for the main intent of the study.
  /// </summary>
  public static class ResearchStudyClassificationTypeCodes
  {
    /// <summary>
    /// Category
    /// </summary>
    public static readonly Coding Category = new Coding
    {
      Code = "category",
      Display = "Category",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Keyword
    /// </summary>
    public static readonly Coding Keyword = new Coding
    {
      Code = "keyword",
      Display = "Keyword",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };
    /// <summary>
    /// Phase
    /// </summary>
    public static readonly Coding Phase = new Coding
    {
      Code = "phase",
      Display = "Phase",
      System = "http://hl7.org/fhir/research-study-classifiers"
    };

    /// <summary>
    /// Literal for code: Category
    /// </summary>
    public const string LiteralCategory = "category";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersCategory
    /// </summary>
    public const string LiteralResearchStudyClassifiersCategory = "http://hl7.org/fhir/research-study-classifiers#category";

    /// <summary>
    /// Literal for code: Keyword
    /// </summary>
    public const string LiteralKeyword = "keyword";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersKeyword
    /// </summary>
    public const string LiteralResearchStudyClassifiersKeyword = "http://hl7.org/fhir/research-study-classifiers#keyword";

    /// <summary>
    /// Literal for code: Phase
    /// </summary>
    public const string LiteralPhase = "phase";

    /// <summary>
    /// Literal for code: ResearchStudyClassifiersPhase
    /// </summary>
    public const string LiteralResearchStudyClassifiersPhase = "http://hl7.org/fhir/research-study-classifiers#phase";

    /// <summary>
    /// Dictionary for looking up ResearchStudyClassificationType Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "category", Category }, 
      { "http://hl7.org/fhir/research-study-classifiers#category", Category }, 
      { "keyword", Keyword }, 
      { "http://hl7.org/fhir/research-study-classifiers#keyword", Keyword }, 
      { "phase", Phase }, 
      { "http://hl7.org/fhir/research-study-classifiers#phase", Phase }, 
    };
  };
}
