// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0
  // Option: "NAMESPACE" = "fhirCsR4B"

using System;
using System.Buffers;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using fhirCsR4B.Models;

namespace fhirCsR4B.Serialization
{
  /// <summary>
  /// Interface for indicating FHIR XML Serialization is possible.
  /// </summary>
  public interface IFhirXmlSerializable
  {
    /// <summary>
    /// Serialize to an XML object
    /// </summary>
    void SerializeXml(XmlWriter writer, XmlWriterSettings options, bool includeStartObject);
    /// <summary>
    /// Parse an open XML object into the current object.
    /// </summary>
    void DeserializeXml(ref XmlReader reader, XmlReaderSettings options);
    /// <summary>
    /// Parse a specific property from an open XML object into a field in the current object.
    /// </summary>
    void DeserializeXmlProperty(ref XmlReader reader, XmlReaderSettings options, string propertyName);
  }
}
